// Code generated by ent, DO NOT EDIT.

package flashcardreview

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the flashcardreview type in the database.
	Label = "flashcard_review"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldFlashcardID holds the string denoting the flashcard_id field in the database.
	FieldFlashcardID = "flashcard_id"
	// FieldEaseFactor holds the string denoting the ease_factor field in the database.
	FieldEaseFactor = "ease_factor"
	// FieldInterval holds the string denoting the interval field in the database.
	FieldInterval = "interval"
	// FieldDueAt holds the string denoting the due_at field in the database.
	FieldDueAt = "due_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldLearningStep holds the string denoting the learning_step field in the database.
	FieldLearningStep = "learning_step"
	// FieldReviewCount holds the string denoting the review_count field in the database.
	FieldReviewCount = "review_count"
	// FieldLapseCount holds the string denoting the lapse_count field in the database.
	FieldLapseCount = "lapse_count"
	// FieldLastReviewedAt holds the string denoting the last_reviewed_at field in the database.
	FieldLastReviewedAt = "last_reviewed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeFlashcard holds the string denoting the flashcard edge name in mutations.
	EdgeFlashcard = "flashcard"
	// Table holds the table name of the flashcardreview in the database.
	Table = "flashcard_reviews"
	// FlashcardTable is the table that holds the flashcard relation/edge.
	FlashcardTable = "flashcard_reviews"
	// FlashcardInverseTable is the table name for the Flashcard entity.
	// It exists in this package in order to avoid circular dependency with the "flashcard" package.
	FlashcardInverseTable = "flashcards"
	// FlashcardColumn is the table column denoting the flashcard relation/edge.
	FlashcardColumn = "flashcard_id"
)

// Columns holds all SQL columns for flashcardreview fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldFlashcardID,
	FieldEaseFactor,
	FieldInterval,
	FieldDueAt,
	FieldStatus,
	FieldLearningStep,
	FieldReviewCount,
	FieldLapseCount,
	FieldLastReviewedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(string) error
	// DefaultEaseFactor holds the default value on creation for the "ease_factor" field.
	DefaultEaseFactor float64
	// EaseFactorValidator is a validator for the "ease_factor" field. It is called by the builders before save.
	EaseFactorValidator func(float64) error
	// DefaultInterval holds the default value on creation for the "interval" field.
	DefaultInterval int
	// IntervalValidator is a validator for the "interval" field. It is called by the builders before save.
	IntervalValidator func(int) error
	// DefaultDueAt holds the default value on creation for the "due_at" field.
	DefaultDueAt func() time.Time
	// DefaultLearningStep holds the default value on creation for the "learning_step" field.
	DefaultLearningStep int
	// LearningStepValidator is a validator for the "learning_step" field. It is called by the builders before save.
	LearningStepValidator func(int) error
	// DefaultReviewCount holds the default value on creation for the "review_count" field.
	DefaultReviewCount int
	// ReviewCountValidator is a validator for the "review_count" field. It is called by the builders before save.
	ReviewCountValidator func(int) error
	// DefaultLapseCount holds the default value on creation for the "lapse_count" field.
	DefaultLapseCount int
	// LapseCountValidator is a validator for the "lapse_count" field. It is called by the builders before save.
	LapseCountValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusNew is the default value of the Status enum.
const DefaultStatus = StatusNew

// Status values.
const (
	StatusNew        Status = "new"
	StatusLearning   Status = "learning"
	StatusReview     Status = "review"
	StatusRelearning Status = "relearning"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusNew, StatusLearning, StatusReview, StatusRelearning:
		return nil
	default:
		return fmt.Errorf("flashcardreview: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the FlashcardReview queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByFlashcardID orders the results by the flashcard_id field.
func ByFlashcardID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFlashcardID, opts...).ToFunc()
}

// ByEaseFactor orders the results by the ease_factor field.
func ByEaseFactor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEaseFactor, opts...).ToFunc()
}

// ByInterval orders the results by the interval field.
func ByInterval(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInterval, opts...).ToFunc()
}

// ByDueAt orders the results by the due_at field.
func ByDueAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDueAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByLearningStep orders the results by the learning_step field.
func ByLearningStep(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLearningStep, opts...).ToFunc()
}

// ByReviewCount orders the results by the review_count field.
func ByReviewCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewCount, opts...).ToFunc()
}

// ByLapseCount orders the results by the lapse_count field.
func ByLapseCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLapseCount, opts...).ToFunc()
}

// ByLastReviewedAt orders the results by the last_reviewed_at field.
func ByLastReviewedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastReviewedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByFlashcardField orders the results by flashcard field.
func ByFlashcardField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFlashcardStep(), sql.OrderByField(field, opts...))
	}
}
func newFlashcardStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FlashcardInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, FlashcardTable, FlashcardColumn),
	)
}
