// Code generated by ent, DO NOT EDIT.

package flashcardreview

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/quanphung1120/advanced-quiz-be/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldUserID, v))
}

// FlashcardID applies equality check predicate on the "flashcard_id" field. It's identical to FlashcardIDEQ.
func FlashcardID(v uuid.UUID) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldFlashcardID, v))
}

// EaseFactor applies equality check predicate on the "ease_factor" field. It's identical to EaseFactorEQ.
func EaseFactor(v float64) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldEaseFactor, v))
}

// Interval applies equality check predicate on the "interval" field. It's identical to IntervalEQ.
func Interval(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldInterval, v))
}

// DueAt applies equality check predicate on the "due_at" field. It's identical to DueAtEQ.
func DueAt(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldDueAt, v))
}

// LearningStep applies equality check predicate on the "learning_step" field. It's identical to LearningStepEQ.
func LearningStep(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldLearningStep, v))
}

// ReviewCount applies equality check predicate on the "review_count" field. It's identical to ReviewCountEQ.
func ReviewCount(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldReviewCount, v))
}

// LapseCount applies equality check predicate on the "lapse_count" field. It's identical to LapseCountEQ.
func LapseCount(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldLapseCount, v))
}

// LastReviewedAt applies equality check predicate on the "last_reviewed_at" field. It's identical to LastReviewedAtEQ.
func LastReviewedAt(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldLastReviewedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldContainsFold(FieldUserID, v))
}

// FlashcardIDEQ applies the EQ predicate on the "flashcard_id" field.
func FlashcardIDEQ(v uuid.UUID) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldFlashcardID, v))
}

// FlashcardIDNEQ applies the NEQ predicate on the "flashcard_id" field.
func FlashcardIDNEQ(v uuid.UUID) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNEQ(FieldFlashcardID, v))
}

// FlashcardIDIn applies the In predicate on the "flashcard_id" field.
func FlashcardIDIn(vs ...uuid.UUID) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldIn(FieldFlashcardID, vs...))
}

// FlashcardIDNotIn applies the NotIn predicate on the "flashcard_id" field.
func FlashcardIDNotIn(vs ...uuid.UUID) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNotIn(FieldFlashcardID, vs...))
}

// EaseFactorEQ applies the EQ predicate on the "ease_factor" field.
func EaseFactorEQ(v float64) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldEaseFactor, v))
}

// EaseFactorNEQ applies the NEQ predicate on the "ease_factor" field.
func EaseFactorNEQ(v float64) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNEQ(FieldEaseFactor, v))
}

// EaseFactorIn applies the In predicate on the "ease_factor" field.
func EaseFactorIn(vs ...float64) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldIn(FieldEaseFactor, vs...))
}

// EaseFactorNotIn applies the NotIn predicate on the "ease_factor" field.
func EaseFactorNotIn(vs ...float64) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNotIn(FieldEaseFactor, vs...))
}

// EaseFactorGT applies the GT predicate on the "ease_factor" field.
func EaseFactorGT(v float64) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldGT(FieldEaseFactor, v))
}

// EaseFactorGTE applies the GTE predicate on the "ease_factor" field.
func EaseFactorGTE(v float64) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldGTE(FieldEaseFactor, v))
}

// EaseFactorLT applies the LT predicate on the "ease_factor" field.
func EaseFactorLT(v float64) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldLT(FieldEaseFactor, v))
}

// EaseFactorLTE applies the LTE predicate on the "ease_factor" field.
func EaseFactorLTE(v float64) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldLTE(FieldEaseFactor, v))
}

// IntervalEQ applies the EQ predicate on the "interval" field.
func IntervalEQ(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldInterval, v))
}

// IntervalNEQ applies the NEQ predicate on the "interval" field.
func IntervalNEQ(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNEQ(FieldInterval, v))
}

// IntervalIn applies the In predicate on the "interval" field.
func IntervalIn(vs ...int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldIn(FieldInterval, vs...))
}

// IntervalNotIn applies the NotIn predicate on the "interval" field.
func IntervalNotIn(vs ...int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNotIn(FieldInterval, vs...))
}

// IntervalGT applies the GT predicate on the "interval" field.
func IntervalGT(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldGT(FieldInterval, v))
}

// IntervalGTE applies the GTE predicate on the "interval" field.
func IntervalGTE(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldGTE(FieldInterval, v))
}

// IntervalLT applies the LT predicate on the "interval" field.
func IntervalLT(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldLT(FieldInterval, v))
}

// IntervalLTE applies the LTE predicate on the "interval" field.
func IntervalLTE(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldLTE(FieldInterval, v))
}

// DueAtEQ applies the EQ predicate on the "due_at" field.
func DueAtEQ(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldDueAt, v))
}

// DueAtNEQ applies the NEQ predicate on the "due_at" field.
func DueAtNEQ(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNEQ(FieldDueAt, v))
}

// DueAtIn applies the In predicate on the "due_at" field.
func DueAtIn(vs ...time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldIn(FieldDueAt, vs...))
}

// DueAtNotIn applies the NotIn predicate on the "due_at" field.
func DueAtNotIn(vs ...time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNotIn(FieldDueAt, vs...))
}

// DueAtGT applies the GT predicate on the "due_at" field.
func DueAtGT(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldGT(FieldDueAt, v))
}

// DueAtGTE applies the GTE predicate on the "due_at" field.
func DueAtGTE(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldGTE(FieldDueAt, v))
}

// DueAtLT applies the LT predicate on the "due_at" field.
func DueAtLT(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldLT(FieldDueAt, v))
}

// DueAtLTE applies the LTE predicate on the "due_at" field.
func DueAtLTE(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldLTE(FieldDueAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNotIn(FieldStatus, vs...))
}

// LearningStepEQ applies the EQ predicate on the "learning_step" field.
func LearningStepEQ(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldLearningStep, v))
}

// LearningStepNEQ applies the NEQ predicate on the "learning_step" field.
func LearningStepNEQ(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNEQ(FieldLearningStep, v))
}

// LearningStepIn applies the In predicate on the "learning_step" field.
func LearningStepIn(vs ...int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldIn(FieldLearningStep, vs...))
}

// LearningStepNotIn applies the NotIn predicate on the "learning_step" field.
func LearningStepNotIn(vs ...int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNotIn(FieldLearningStep, vs...))
}

// LearningStepGT applies the GT predicate on the "learning_step" field.
func LearningStepGT(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldGT(FieldLearningStep, v))
}

// LearningStepGTE applies the GTE predicate on the "learning_step" field.
func LearningStepGTE(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldGTE(FieldLearningStep, v))
}

// LearningStepLT applies the LT predicate on the "learning_step" field.
func LearningStepLT(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldLT(FieldLearningStep, v))
}

// LearningStepLTE applies the LTE predicate on the "learning_step" field.
func LearningStepLTE(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldLTE(FieldLearningStep, v))
}

// ReviewCountEQ applies the EQ predicate on the "review_count" field.
func ReviewCountEQ(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldReviewCount, v))
}

// ReviewCountNEQ applies the NEQ predicate on the "review_count" field.
func ReviewCountNEQ(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNEQ(FieldReviewCount, v))
}

// ReviewCountIn applies the In predicate on the "review_count" field.
func ReviewCountIn(vs ...int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldIn(FieldReviewCount, vs...))
}

// ReviewCountNotIn applies the NotIn predicate on the "review_count" field.
func ReviewCountNotIn(vs ...int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNotIn(FieldReviewCount, vs...))
}

// ReviewCountGT applies the GT predicate on the "review_count" field.
func ReviewCountGT(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldGT(FieldReviewCount, v))
}

// ReviewCountGTE applies the GTE predicate on the "review_count" field.
func ReviewCountGTE(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldGTE(FieldReviewCount, v))
}

// ReviewCountLT applies the LT predicate on the "review_count" field.
func ReviewCountLT(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldLT(FieldReviewCount, v))
}

// ReviewCountLTE applies the LTE predicate on the "review_count" field.
func ReviewCountLTE(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldLTE(FieldReviewCount, v))
}

// LapseCountEQ applies the EQ predicate on the "lapse_count" field.
func LapseCountEQ(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldLapseCount, v))
}

// LapseCountNEQ applies the NEQ predicate on the "lapse_count" field.
func LapseCountNEQ(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNEQ(FieldLapseCount, v))
}

// LapseCountIn applies the In predicate on the "lapse_count" field.
func LapseCountIn(vs ...int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldIn(FieldLapseCount, vs...))
}

// LapseCountNotIn applies the NotIn predicate on the "lapse_count" field.
func LapseCountNotIn(vs ...int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNotIn(FieldLapseCount, vs...))
}

// LapseCountGT applies the GT predicate on the "lapse_count" field.
func LapseCountGT(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldGT(FieldLapseCount, v))
}

// LapseCountGTE applies the GTE predicate on the "lapse_count" field.
func LapseCountGTE(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldGTE(FieldLapseCount, v))
}

// LapseCountLT applies the LT predicate on the "lapse_count" field.
func LapseCountLT(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldLT(FieldLapseCount, v))
}

// LapseCountLTE applies the LTE predicate on the "lapse_count" field.
func LapseCountLTE(v int) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldLTE(FieldLapseCount, v))
}

// LastReviewedAtEQ applies the EQ predicate on the "last_reviewed_at" field.
func LastReviewedAtEQ(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldLastReviewedAt, v))
}

// LastReviewedAtNEQ applies the NEQ predicate on the "last_reviewed_at" field.
func LastReviewedAtNEQ(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNEQ(FieldLastReviewedAt, v))
}

// LastReviewedAtIn applies the In predicate on the "last_reviewed_at" field.
func LastReviewedAtIn(vs ...time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldIn(FieldLastReviewedAt, vs...))
}

// LastReviewedAtNotIn applies the NotIn predicate on the "last_reviewed_at" field.
func LastReviewedAtNotIn(vs ...time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNotIn(FieldLastReviewedAt, vs...))
}

// LastReviewedAtGT applies the GT predicate on the "last_reviewed_at" field.
func LastReviewedAtGT(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldGT(FieldLastReviewedAt, v))
}

// LastReviewedAtGTE applies the GTE predicate on the "last_reviewed_at" field.
func LastReviewedAtGTE(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldGTE(FieldLastReviewedAt, v))
}

// LastReviewedAtLT applies the LT predicate on the "last_reviewed_at" field.
func LastReviewedAtLT(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldLT(FieldLastReviewedAt, v))
}

// LastReviewedAtLTE applies the LTE predicate on the "last_reviewed_at" field.
func LastReviewedAtLTE(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldLTE(FieldLastReviewedAt, v))
}

// LastReviewedAtIsNil applies the IsNil predicate on the "last_reviewed_at" field.
func LastReviewedAtIsNil() predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldIsNull(FieldLastReviewedAt))
}

// LastReviewedAtNotNil applies the NotNil predicate on the "last_reviewed_at" field.
func LastReviewedAtNotNil() predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNotNull(FieldLastReviewedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasFlashcard applies the HasEdge predicate on the "flashcard" edge.
func HasFlashcard() predicate.FlashcardReview {
	return predicate.FlashcardReview(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FlashcardTable, FlashcardColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFlashcardWith applies the HasEdge predicate on the "flashcard" edge with a given conditions (other predicates).
func HasFlashcardWith(preds ...predicate.Flashcard) predicate.FlashcardReview {
	return predicate.FlashcardReview(func(s *sql.Selector) {
		step := newFlashcardStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FlashcardReview) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FlashcardReview) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FlashcardReview) predicate.FlashcardReview {
	return predicate.FlashcardReview(sql.NotPredicates(p))
}
