// Code generated by ent, DO NOT EDIT.

package collection

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the collection type in the database.
	Label = "collection"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldIsPublic holds the string denoting the is_public field in the database.
	FieldIsPublic = "is_public"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeCollaborators holds the string denoting the collaborators edge name in mutations.
	EdgeCollaborators = "collaborators"
	// EdgeFlashcards holds the string denoting the flashcards edge name in mutations.
	EdgeFlashcards = "flashcards"
	// Table holds the table name of the collection in the database.
	Table = "collections"
	// CollaboratorsTable is the table that holds the collaborators relation/edge.
	CollaboratorsTable = "collection_collaborators"
	// CollaboratorsInverseTable is the table name for the CollectionCollaborator entity.
	// It exists in this package in order to avoid circular dependency with the "collectioncollaborator" package.
	CollaboratorsInverseTable = "collection_collaborators"
	// CollaboratorsColumn is the table column denoting the collaborators relation/edge.
	CollaboratorsColumn = "collection_id"
	// FlashcardsTable is the table that holds the flashcards relation/edge.
	FlashcardsTable = "flashcards"
	// FlashcardsInverseTable is the table name for the Flashcard entity.
	// It exists in this package in order to avoid circular dependency with the "flashcard" package.
	FlashcardsInverseTable = "flashcards"
	// FlashcardsColumn is the table column denoting the flashcards relation/edge.
	FlashcardsColumn = "collection_id"
)

// Columns holds all SQL columns for collection fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldOwnerID,
	FieldIsPublic,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// OwnerIDValidator is a validator for the "owner_id" field. It is called by the builders before save.
	OwnerIDValidator func(string) error
	// DefaultIsPublic holds the default value on creation for the "is_public" field.
	DefaultIsPublic bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Collection queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByOwnerID orders the results by the owner_id field.
func ByOwnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerID, opts...).ToFunc()
}

// ByIsPublic orders the results by the is_public field.
func ByIsPublic(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPublic, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCollaboratorsCount orders the results by collaborators count.
func ByCollaboratorsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCollaboratorsStep(), opts...)
	}
}

// ByCollaborators orders the results by collaborators terms.
func ByCollaborators(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCollaboratorsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFlashcardsCount orders the results by flashcards count.
func ByFlashcardsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFlashcardsStep(), opts...)
	}
}

// ByFlashcards orders the results by flashcards terms.
func ByFlashcards(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFlashcardsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCollaboratorsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CollaboratorsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CollaboratorsTable, CollaboratorsColumn),
	)
}
func newFlashcardsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FlashcardsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FlashcardsTable, FlashcardsColumn),
	)
}
