// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CollectionsColumns holds the columns for the "collections" table.
	CollectionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "description", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "owner_id", Type: field.TypeString, Size: 255},
		{Name: "is_public", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CollectionsTable holds the schema information for the "collections" table.
	CollectionsTable = &schema.Table{
		Name:       "collections",
		Columns:    CollectionsColumns,
		PrimaryKey: []*schema.Column{CollectionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "collection_owner_id",
				Unique:  true,
				Columns: []*schema.Column{CollectionsColumns[3]},
			},
		},
	}
	// CollectionCollaboratorsColumns holds the columns for the "collection_collaborators" table.
	CollectionCollaboratorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeString, Size: 255},
		{Name: "role", Type: field.TypeString, Size: 50, Default: "viewer"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "collection_id", Type: field.TypeUUID},
	}
	// CollectionCollaboratorsTable holds the schema information for the "collection_collaborators" table.
	CollectionCollaboratorsTable = &schema.Table{
		Name:       "collection_collaborators",
		Columns:    CollectionCollaboratorsColumns,
		PrimaryKey: []*schema.Column{CollectionCollaboratorsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "collection_collaborators_collections_collaborators",
				Columns:    []*schema.Column{CollectionCollaboratorsColumns[4]},
				RefColumns: []*schema.Column{CollectionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// FlashcardsColumns holds the columns for the "flashcards" table.
	FlashcardsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "question", Type: field.TypeString},
		{Name: "answer", Type: field.TypeString},
		{Name: "type", Type: field.TypeString, Size: 50, Default: "simple"},
		{Name: "created_by", Type: field.TypeString, Size: 255},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "collection_id", Type: field.TypeUUID},
	}
	// FlashcardsTable holds the schema information for the "flashcards" table.
	FlashcardsTable = &schema.Table{
		Name:       "flashcards",
		Columns:    FlashcardsColumns,
		PrimaryKey: []*schema.Column{FlashcardsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "flashcards_collections_flashcards",
				Columns:    []*schema.Column{FlashcardsColumns[7]},
				RefColumns: []*schema.Column{CollectionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CollectionsTable,
		CollectionCollaboratorsTable,
		FlashcardsTable,
	}
)

func init() {
	CollectionCollaboratorsTable.ForeignKeys[0].RefTable = CollectionsTable
	FlashcardsTable.ForeignKeys[0].RefTable = CollectionsTable
}
