// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/quanphung1120/advanced-quiz-be/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/quanphung1120/advanced-quiz-be/ent/collection"
	"github.com/quanphung1120/advanced-quiz-be/ent/collectioncollaborator"
	"github.com/quanphung1120/advanced-quiz-be/ent/flashcard"
	"github.com/quanphung1120/advanced-quiz-be/ent/flashcardreview"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Collection is the client for interacting with the Collection builders.
	Collection *CollectionClient
	// CollectionCollaborator is the client for interacting with the CollectionCollaborator builders.
	CollectionCollaborator *CollectionCollaboratorClient
	// Flashcard is the client for interacting with the Flashcard builders.
	Flashcard *FlashcardClient
	// FlashcardReview is the client for interacting with the FlashcardReview builders.
	FlashcardReview *FlashcardReviewClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Collection = NewCollectionClient(c.config)
	c.CollectionCollaborator = NewCollectionCollaboratorClient(c.config)
	c.Flashcard = NewFlashcardClient(c.config)
	c.FlashcardReview = NewFlashcardReviewClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                    ctx,
		config:                 cfg,
		Collection:             NewCollectionClient(cfg),
		CollectionCollaborator: NewCollectionCollaboratorClient(cfg),
		Flashcard:              NewFlashcardClient(cfg),
		FlashcardReview:        NewFlashcardReviewClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                    ctx,
		config:                 cfg,
		Collection:             NewCollectionClient(cfg),
		CollectionCollaborator: NewCollectionCollaboratorClient(cfg),
		Flashcard:              NewFlashcardClient(cfg),
		FlashcardReview:        NewFlashcardReviewClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Collection.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Collection.Use(hooks...)
	c.CollectionCollaborator.Use(hooks...)
	c.Flashcard.Use(hooks...)
	c.FlashcardReview.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Collection.Intercept(interceptors...)
	c.CollectionCollaborator.Intercept(interceptors...)
	c.Flashcard.Intercept(interceptors...)
	c.FlashcardReview.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CollectionMutation:
		return c.Collection.mutate(ctx, m)
	case *CollectionCollaboratorMutation:
		return c.CollectionCollaborator.mutate(ctx, m)
	case *FlashcardMutation:
		return c.Flashcard.mutate(ctx, m)
	case *FlashcardReviewMutation:
		return c.FlashcardReview.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CollectionClient is a client for the Collection schema.
type CollectionClient struct {
	config
}

// NewCollectionClient returns a client for the Collection from the given config.
func NewCollectionClient(c config) *CollectionClient {
	return &CollectionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `collection.Hooks(f(g(h())))`.
func (c *CollectionClient) Use(hooks ...Hook) {
	c.hooks.Collection = append(c.hooks.Collection, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `collection.Intercept(f(g(h())))`.
func (c *CollectionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Collection = append(c.inters.Collection, interceptors...)
}

// Create returns a builder for creating a Collection entity.
func (c *CollectionClient) Create() *CollectionCreate {
	mutation := newCollectionMutation(c.config, OpCreate)
	return &CollectionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Collection entities.
func (c *CollectionClient) CreateBulk(builders ...*CollectionCreate) *CollectionCreateBulk {
	return &CollectionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CollectionClient) MapCreateBulk(slice any, setFunc func(*CollectionCreate, int)) *CollectionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CollectionCreateBulk{err: fmt.Errorf("calling to CollectionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CollectionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CollectionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Collection.
func (c *CollectionClient) Update() *CollectionUpdate {
	mutation := newCollectionMutation(c.config, OpUpdate)
	return &CollectionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CollectionClient) UpdateOne(_m *Collection) *CollectionUpdateOne {
	mutation := newCollectionMutation(c.config, OpUpdateOne, withCollection(_m))
	return &CollectionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CollectionClient) UpdateOneID(id uuid.UUID) *CollectionUpdateOne {
	mutation := newCollectionMutation(c.config, OpUpdateOne, withCollectionID(id))
	return &CollectionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Collection.
func (c *CollectionClient) Delete() *CollectionDelete {
	mutation := newCollectionMutation(c.config, OpDelete)
	return &CollectionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CollectionClient) DeleteOne(_m *Collection) *CollectionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CollectionClient) DeleteOneID(id uuid.UUID) *CollectionDeleteOne {
	builder := c.Delete().Where(collection.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CollectionDeleteOne{builder}
}

// Query returns a query builder for Collection.
func (c *CollectionClient) Query() *CollectionQuery {
	return &CollectionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCollection},
		inters: c.Interceptors(),
	}
}

// Get returns a Collection entity by its id.
func (c *CollectionClient) Get(ctx context.Context, id uuid.UUID) (*Collection, error) {
	return c.Query().Where(collection.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CollectionClient) GetX(ctx context.Context, id uuid.UUID) *Collection {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCollaborators queries the collaborators edge of a Collection.
func (c *CollectionClient) QueryCollaborators(_m *Collection) *CollectionCollaboratorQuery {
	query := (&CollectionCollaboratorClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(collection.Table, collection.FieldID, id),
			sqlgraph.To(collectioncollaborator.Table, collectioncollaborator.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, collection.CollaboratorsTable, collection.CollaboratorsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryFlashcards queries the flashcards edge of a Collection.
func (c *CollectionClient) QueryFlashcards(_m *Collection) *FlashcardQuery {
	query := (&FlashcardClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(collection.Table, collection.FieldID, id),
			sqlgraph.To(flashcard.Table, flashcard.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, collection.FlashcardsTable, collection.FlashcardsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CollectionClient) Hooks() []Hook {
	return c.hooks.Collection
}

// Interceptors returns the client interceptors.
func (c *CollectionClient) Interceptors() []Interceptor {
	return c.inters.Collection
}

func (c *CollectionClient) mutate(ctx context.Context, m *CollectionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CollectionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CollectionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CollectionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CollectionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Collection mutation op: %q", m.Op())
	}
}

// CollectionCollaboratorClient is a client for the CollectionCollaborator schema.
type CollectionCollaboratorClient struct {
	config
}

// NewCollectionCollaboratorClient returns a client for the CollectionCollaborator from the given config.
func NewCollectionCollaboratorClient(c config) *CollectionCollaboratorClient {
	return &CollectionCollaboratorClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `collectioncollaborator.Hooks(f(g(h())))`.
func (c *CollectionCollaboratorClient) Use(hooks ...Hook) {
	c.hooks.CollectionCollaborator = append(c.hooks.CollectionCollaborator, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `collectioncollaborator.Intercept(f(g(h())))`.
func (c *CollectionCollaboratorClient) Intercept(interceptors ...Interceptor) {
	c.inters.CollectionCollaborator = append(c.inters.CollectionCollaborator, interceptors...)
}

// Create returns a builder for creating a CollectionCollaborator entity.
func (c *CollectionCollaboratorClient) Create() *CollectionCollaboratorCreate {
	mutation := newCollectionCollaboratorMutation(c.config, OpCreate)
	return &CollectionCollaboratorCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CollectionCollaborator entities.
func (c *CollectionCollaboratorClient) CreateBulk(builders ...*CollectionCollaboratorCreate) *CollectionCollaboratorCreateBulk {
	return &CollectionCollaboratorCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CollectionCollaboratorClient) MapCreateBulk(slice any, setFunc func(*CollectionCollaboratorCreate, int)) *CollectionCollaboratorCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CollectionCollaboratorCreateBulk{err: fmt.Errorf("calling to CollectionCollaboratorClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CollectionCollaboratorCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CollectionCollaboratorCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CollectionCollaborator.
func (c *CollectionCollaboratorClient) Update() *CollectionCollaboratorUpdate {
	mutation := newCollectionCollaboratorMutation(c.config, OpUpdate)
	return &CollectionCollaboratorUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CollectionCollaboratorClient) UpdateOne(_m *CollectionCollaborator) *CollectionCollaboratorUpdateOne {
	mutation := newCollectionCollaboratorMutation(c.config, OpUpdateOne, withCollectionCollaborator(_m))
	return &CollectionCollaboratorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CollectionCollaboratorClient) UpdateOneID(id uuid.UUID) *CollectionCollaboratorUpdateOne {
	mutation := newCollectionCollaboratorMutation(c.config, OpUpdateOne, withCollectionCollaboratorID(id))
	return &CollectionCollaboratorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CollectionCollaborator.
func (c *CollectionCollaboratorClient) Delete() *CollectionCollaboratorDelete {
	mutation := newCollectionCollaboratorMutation(c.config, OpDelete)
	return &CollectionCollaboratorDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CollectionCollaboratorClient) DeleteOne(_m *CollectionCollaborator) *CollectionCollaboratorDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CollectionCollaboratorClient) DeleteOneID(id uuid.UUID) *CollectionCollaboratorDeleteOne {
	builder := c.Delete().Where(collectioncollaborator.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CollectionCollaboratorDeleteOne{builder}
}

// Query returns a query builder for CollectionCollaborator.
func (c *CollectionCollaboratorClient) Query() *CollectionCollaboratorQuery {
	return &CollectionCollaboratorQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCollectionCollaborator},
		inters: c.Interceptors(),
	}
}

// Get returns a CollectionCollaborator entity by its id.
func (c *CollectionCollaboratorClient) Get(ctx context.Context, id uuid.UUID) (*CollectionCollaborator, error) {
	return c.Query().Where(collectioncollaborator.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CollectionCollaboratorClient) GetX(ctx context.Context, id uuid.UUID) *CollectionCollaborator {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCollection queries the collection edge of a CollectionCollaborator.
func (c *CollectionCollaboratorClient) QueryCollection(_m *CollectionCollaborator) *CollectionQuery {
	query := (&CollectionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(collectioncollaborator.Table, collectioncollaborator.FieldID, id),
			sqlgraph.To(collection.Table, collection.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, collectioncollaborator.CollectionTable, collectioncollaborator.CollectionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CollectionCollaboratorClient) Hooks() []Hook {
	return c.hooks.CollectionCollaborator
}

// Interceptors returns the client interceptors.
func (c *CollectionCollaboratorClient) Interceptors() []Interceptor {
	return c.inters.CollectionCollaborator
}

func (c *CollectionCollaboratorClient) mutate(ctx context.Context, m *CollectionCollaboratorMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CollectionCollaboratorCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CollectionCollaboratorUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CollectionCollaboratorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CollectionCollaboratorDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CollectionCollaborator mutation op: %q", m.Op())
	}
}

// FlashcardClient is a client for the Flashcard schema.
type FlashcardClient struct {
	config
}

// NewFlashcardClient returns a client for the Flashcard from the given config.
func NewFlashcardClient(c config) *FlashcardClient {
	return &FlashcardClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `flashcard.Hooks(f(g(h())))`.
func (c *FlashcardClient) Use(hooks ...Hook) {
	c.hooks.Flashcard = append(c.hooks.Flashcard, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `flashcard.Intercept(f(g(h())))`.
func (c *FlashcardClient) Intercept(interceptors ...Interceptor) {
	c.inters.Flashcard = append(c.inters.Flashcard, interceptors...)
}

// Create returns a builder for creating a Flashcard entity.
func (c *FlashcardClient) Create() *FlashcardCreate {
	mutation := newFlashcardMutation(c.config, OpCreate)
	return &FlashcardCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Flashcard entities.
func (c *FlashcardClient) CreateBulk(builders ...*FlashcardCreate) *FlashcardCreateBulk {
	return &FlashcardCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FlashcardClient) MapCreateBulk(slice any, setFunc func(*FlashcardCreate, int)) *FlashcardCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FlashcardCreateBulk{err: fmt.Errorf("calling to FlashcardClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FlashcardCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FlashcardCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Flashcard.
func (c *FlashcardClient) Update() *FlashcardUpdate {
	mutation := newFlashcardMutation(c.config, OpUpdate)
	return &FlashcardUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FlashcardClient) UpdateOne(_m *Flashcard) *FlashcardUpdateOne {
	mutation := newFlashcardMutation(c.config, OpUpdateOne, withFlashcard(_m))
	return &FlashcardUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FlashcardClient) UpdateOneID(id uuid.UUID) *FlashcardUpdateOne {
	mutation := newFlashcardMutation(c.config, OpUpdateOne, withFlashcardID(id))
	return &FlashcardUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Flashcard.
func (c *FlashcardClient) Delete() *FlashcardDelete {
	mutation := newFlashcardMutation(c.config, OpDelete)
	return &FlashcardDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FlashcardClient) DeleteOne(_m *Flashcard) *FlashcardDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FlashcardClient) DeleteOneID(id uuid.UUID) *FlashcardDeleteOne {
	builder := c.Delete().Where(flashcard.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FlashcardDeleteOne{builder}
}

// Query returns a query builder for Flashcard.
func (c *FlashcardClient) Query() *FlashcardQuery {
	return &FlashcardQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFlashcard},
		inters: c.Interceptors(),
	}
}

// Get returns a Flashcard entity by its id.
func (c *FlashcardClient) Get(ctx context.Context, id uuid.UUID) (*Flashcard, error) {
	return c.Query().Where(flashcard.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FlashcardClient) GetX(ctx context.Context, id uuid.UUID) *Flashcard {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCollection queries the collection edge of a Flashcard.
func (c *FlashcardClient) QueryCollection(_m *Flashcard) *CollectionQuery {
	query := (&CollectionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(flashcard.Table, flashcard.FieldID, id),
			sqlgraph.To(collection.Table, collection.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, flashcard.CollectionTable, flashcard.CollectionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryReviews queries the reviews edge of a Flashcard.
func (c *FlashcardClient) QueryReviews(_m *Flashcard) *FlashcardReviewQuery {
	query := (&FlashcardReviewClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(flashcard.Table, flashcard.FieldID, id),
			sqlgraph.To(flashcardreview.Table, flashcardreview.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, flashcard.ReviewsTable, flashcard.ReviewsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *FlashcardClient) Hooks() []Hook {
	return c.hooks.Flashcard
}

// Interceptors returns the client interceptors.
func (c *FlashcardClient) Interceptors() []Interceptor {
	return c.inters.Flashcard
}

func (c *FlashcardClient) mutate(ctx context.Context, m *FlashcardMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FlashcardCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FlashcardUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FlashcardUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FlashcardDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Flashcard mutation op: %q", m.Op())
	}
}

// FlashcardReviewClient is a client for the FlashcardReview schema.
type FlashcardReviewClient struct {
	config
}

// NewFlashcardReviewClient returns a client for the FlashcardReview from the given config.
func NewFlashcardReviewClient(c config) *FlashcardReviewClient {
	return &FlashcardReviewClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `flashcardreview.Hooks(f(g(h())))`.
func (c *FlashcardReviewClient) Use(hooks ...Hook) {
	c.hooks.FlashcardReview = append(c.hooks.FlashcardReview, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `flashcardreview.Intercept(f(g(h())))`.
func (c *FlashcardReviewClient) Intercept(interceptors ...Interceptor) {
	c.inters.FlashcardReview = append(c.inters.FlashcardReview, interceptors...)
}

// Create returns a builder for creating a FlashcardReview entity.
func (c *FlashcardReviewClient) Create() *FlashcardReviewCreate {
	mutation := newFlashcardReviewMutation(c.config, OpCreate)
	return &FlashcardReviewCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of FlashcardReview entities.
func (c *FlashcardReviewClient) CreateBulk(builders ...*FlashcardReviewCreate) *FlashcardReviewCreateBulk {
	return &FlashcardReviewCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FlashcardReviewClient) MapCreateBulk(slice any, setFunc func(*FlashcardReviewCreate, int)) *FlashcardReviewCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FlashcardReviewCreateBulk{err: fmt.Errorf("calling to FlashcardReviewClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FlashcardReviewCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FlashcardReviewCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for FlashcardReview.
func (c *FlashcardReviewClient) Update() *FlashcardReviewUpdate {
	mutation := newFlashcardReviewMutation(c.config, OpUpdate)
	return &FlashcardReviewUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FlashcardReviewClient) UpdateOne(_m *FlashcardReview) *FlashcardReviewUpdateOne {
	mutation := newFlashcardReviewMutation(c.config, OpUpdateOne, withFlashcardReview(_m))
	return &FlashcardReviewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FlashcardReviewClient) UpdateOneID(id uuid.UUID) *FlashcardReviewUpdateOne {
	mutation := newFlashcardReviewMutation(c.config, OpUpdateOne, withFlashcardReviewID(id))
	return &FlashcardReviewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for FlashcardReview.
func (c *FlashcardReviewClient) Delete() *FlashcardReviewDelete {
	mutation := newFlashcardReviewMutation(c.config, OpDelete)
	return &FlashcardReviewDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FlashcardReviewClient) DeleteOne(_m *FlashcardReview) *FlashcardReviewDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FlashcardReviewClient) DeleteOneID(id uuid.UUID) *FlashcardReviewDeleteOne {
	builder := c.Delete().Where(flashcardreview.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FlashcardReviewDeleteOne{builder}
}

// Query returns a query builder for FlashcardReview.
func (c *FlashcardReviewClient) Query() *FlashcardReviewQuery {
	return &FlashcardReviewQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFlashcardReview},
		inters: c.Interceptors(),
	}
}

// Get returns a FlashcardReview entity by its id.
func (c *FlashcardReviewClient) Get(ctx context.Context, id uuid.UUID) (*FlashcardReview, error) {
	return c.Query().Where(flashcardreview.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FlashcardReviewClient) GetX(ctx context.Context, id uuid.UUID) *FlashcardReview {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryFlashcard queries the flashcard edge of a FlashcardReview.
func (c *FlashcardReviewClient) QueryFlashcard(_m *FlashcardReview) *FlashcardQuery {
	query := (&FlashcardClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(flashcardreview.Table, flashcardreview.FieldID, id),
			sqlgraph.To(flashcard.Table, flashcard.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, flashcardreview.FlashcardTable, flashcardreview.FlashcardColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *FlashcardReviewClient) Hooks() []Hook {
	return c.hooks.FlashcardReview
}

// Interceptors returns the client interceptors.
func (c *FlashcardReviewClient) Interceptors() []Interceptor {
	return c.inters.FlashcardReview
}

func (c *FlashcardReviewClient) mutate(ctx context.Context, m *FlashcardReviewMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FlashcardReviewCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FlashcardReviewUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FlashcardReviewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FlashcardReviewDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown FlashcardReview mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Collection, CollectionCollaborator, Flashcard, FlashcardReview []ent.Hook
	}
	inters struct {
		Collection, CollectionCollaborator, Flashcard, FlashcardReview []ent.Interceptor
	}
)
