// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/quanphung1120/advanced-quiz-be/ent/collection"
	"github.com/quanphung1120/advanced-quiz-be/ent/collectioncollaborator"
)

// CollectionCollaborator is the model entity for the CollectionCollaborator schema.
type CollectionCollaborator struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CollectionID holds the value of the "collection_id" field.
	CollectionID uuid.UUID `json:"collection_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// Role holds the value of the "role" field.
	Role string `json:"role,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CollectionCollaboratorQuery when eager-loading is set.
	Edges        CollectionCollaboratorEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CollectionCollaboratorEdges holds the relations/edges for other nodes in the graph.
type CollectionCollaboratorEdges struct {
	// Collection holds the value of the collection edge.
	Collection *Collection `json:"collection,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CollectionOrErr returns the Collection value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CollectionCollaboratorEdges) CollectionOrErr() (*Collection, error) {
	if e.Collection != nil {
		return e.Collection, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: collection.Label}
	}
	return nil, &NotLoadedError{edge: "collection"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CollectionCollaborator) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case collectioncollaborator.FieldUserID, collectioncollaborator.FieldRole:
			values[i] = new(sql.NullString)
		case collectioncollaborator.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case collectioncollaborator.FieldID, collectioncollaborator.FieldCollectionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CollectionCollaborator fields.
func (_m *CollectionCollaborator) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case collectioncollaborator.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case collectioncollaborator.FieldCollectionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field collection_id", values[i])
			} else if value != nil {
				_m.CollectionID = *value
			}
		case collectioncollaborator.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case collectioncollaborator.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case collectioncollaborator.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CollectionCollaborator.
// This includes values selected through modifiers, order, etc.
func (_m *CollectionCollaborator) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCollection queries the "collection" edge of the CollectionCollaborator entity.
func (_m *CollectionCollaborator) QueryCollection() *CollectionQuery {
	return NewCollectionCollaboratorClient(_m.config).QueryCollection(_m)
}

// Update returns a builder for updating this CollectionCollaborator.
// Note that you need to call CollectionCollaborator.Unwrap() before calling this method if this CollectionCollaborator
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CollectionCollaborator) Update() *CollectionCollaboratorUpdateOne {
	return NewCollectionCollaboratorClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CollectionCollaborator entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CollectionCollaborator) Unwrap() *CollectionCollaborator {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CollectionCollaborator is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CollectionCollaborator) String() string {
	var builder strings.Builder
	builder.WriteString("CollectionCollaborator(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("collection_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CollectionID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CollectionCollaborators is a parsable slice of CollectionCollaborator.
type CollectionCollaborators []*CollectionCollaborator
