// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/quanphung1120/advanced-quiz-be/ent/collection"
	"github.com/quanphung1120/advanced-quiz-be/ent/collectioncollaborator"
	"github.com/quanphung1120/advanced-quiz-be/ent/flashcard"
	"github.com/quanphung1120/advanced-quiz-be/ent/predicate"
)

// CollectionUpdate is the builder for updating Collection entities.
type CollectionUpdate struct {
	config
	hooks    []Hook
	mutation *CollectionMutation
}

// Where appends a list predicates to the CollectionUpdate builder.
func (_u *CollectionUpdate) Where(ps ...predicate.Collection) *CollectionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *CollectionUpdate) SetName(v string) *CollectionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CollectionUpdate) SetNillableName(v *string) *CollectionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CollectionUpdate) SetDescription(v string) *CollectionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CollectionUpdate) SetNillableDescription(v *string) *CollectionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *CollectionUpdate) ClearDescription() *CollectionUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *CollectionUpdate) SetOwnerID(v string) *CollectionUpdate {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *CollectionUpdate) SetNillableOwnerID(v *string) *CollectionUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *CollectionUpdate) SetIsPublic(v bool) *CollectionUpdate {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *CollectionUpdate) SetNillableIsPublic(v *bool) *CollectionUpdate {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CollectionUpdate) SetUpdatedAt(v time.Time) *CollectionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddCollaboratorIDs adds the "collaborators" edge to the CollectionCollaborator entity by IDs.
func (_u *CollectionUpdate) AddCollaboratorIDs(ids ...uuid.UUID) *CollectionUpdate {
	_u.mutation.AddCollaboratorIDs(ids...)
	return _u
}

// AddCollaborators adds the "collaborators" edges to the CollectionCollaborator entity.
func (_u *CollectionUpdate) AddCollaborators(v ...*CollectionCollaborator) *CollectionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCollaboratorIDs(ids...)
}

// AddFlashcardIDs adds the "flashcards" edge to the Flashcard entity by IDs.
func (_u *CollectionUpdate) AddFlashcardIDs(ids ...uuid.UUID) *CollectionUpdate {
	_u.mutation.AddFlashcardIDs(ids...)
	return _u
}

// AddFlashcards adds the "flashcards" edges to the Flashcard entity.
func (_u *CollectionUpdate) AddFlashcards(v ...*Flashcard) *CollectionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFlashcardIDs(ids...)
}

// Mutation returns the CollectionMutation object of the builder.
func (_u *CollectionUpdate) Mutation() *CollectionMutation {
	return _u.mutation
}

// ClearCollaborators clears all "collaborators" edges to the CollectionCollaborator entity.
func (_u *CollectionUpdate) ClearCollaborators() *CollectionUpdate {
	_u.mutation.ClearCollaborators()
	return _u
}

// RemoveCollaboratorIDs removes the "collaborators" edge to CollectionCollaborator entities by IDs.
func (_u *CollectionUpdate) RemoveCollaboratorIDs(ids ...uuid.UUID) *CollectionUpdate {
	_u.mutation.RemoveCollaboratorIDs(ids...)
	return _u
}

// RemoveCollaborators removes "collaborators" edges to CollectionCollaborator entities.
func (_u *CollectionUpdate) RemoveCollaborators(v ...*CollectionCollaborator) *CollectionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCollaboratorIDs(ids...)
}

// ClearFlashcards clears all "flashcards" edges to the Flashcard entity.
func (_u *CollectionUpdate) ClearFlashcards() *CollectionUpdate {
	_u.mutation.ClearFlashcards()
	return _u
}

// RemoveFlashcardIDs removes the "flashcards" edge to Flashcard entities by IDs.
func (_u *CollectionUpdate) RemoveFlashcardIDs(ids ...uuid.UUID) *CollectionUpdate {
	_u.mutation.RemoveFlashcardIDs(ids...)
	return _u
}

// RemoveFlashcards removes "flashcards" edges to Flashcard entities.
func (_u *CollectionUpdate) RemoveFlashcards(v ...*Flashcard) *CollectionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFlashcardIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CollectionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CollectionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CollectionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CollectionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CollectionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := collection.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CollectionUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := collection.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Collection.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OwnerID(); ok {
		if err := collection.OwnerIDValidator(v); err != nil {
			return &ValidationError{Name: "owner_id", err: fmt.Errorf(`ent: validator failed for field "Collection.owner_id": %w`, err)}
		}
	}
	return nil
}

func (_u *CollectionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(collection.Table, collection.Columns, sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(collection.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(collection.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(collection.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(collection.FieldOwnerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(collection.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(collection.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CollaboratorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.CollaboratorsTable,
			Columns: []string{collection.CollaboratorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collectioncollaborator.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCollaboratorsIDs(); len(nodes) > 0 && !_u.mutation.CollaboratorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.CollaboratorsTable,
			Columns: []string{collection.CollaboratorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collectioncollaborator.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollaboratorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.CollaboratorsTable,
			Columns: []string{collection.CollaboratorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collectioncollaborator.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FlashcardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.FlashcardsTable,
			Columns: []string{collection.FlashcardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flashcard.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFlashcardsIDs(); len(nodes) > 0 && !_u.mutation.FlashcardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.FlashcardsTable,
			Columns: []string{collection.FlashcardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flashcard.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlashcardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.FlashcardsTable,
			Columns: []string{collection.FlashcardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flashcard.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{collection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CollectionUpdateOne is the builder for updating a single Collection entity.
type CollectionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CollectionMutation
}

// SetName sets the "name" field.
func (_u *CollectionUpdateOne) SetName(v string) *CollectionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CollectionUpdateOne) SetNillableName(v *string) *CollectionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CollectionUpdateOne) SetDescription(v string) *CollectionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CollectionUpdateOne) SetNillableDescription(v *string) *CollectionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *CollectionUpdateOne) ClearDescription() *CollectionUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *CollectionUpdateOne) SetOwnerID(v string) *CollectionUpdateOne {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *CollectionUpdateOne) SetNillableOwnerID(v *string) *CollectionUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *CollectionUpdateOne) SetIsPublic(v bool) *CollectionUpdateOne {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *CollectionUpdateOne) SetNillableIsPublic(v *bool) *CollectionUpdateOne {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CollectionUpdateOne) SetUpdatedAt(v time.Time) *CollectionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddCollaboratorIDs adds the "collaborators" edge to the CollectionCollaborator entity by IDs.
func (_u *CollectionUpdateOne) AddCollaboratorIDs(ids ...uuid.UUID) *CollectionUpdateOne {
	_u.mutation.AddCollaboratorIDs(ids...)
	return _u
}

// AddCollaborators adds the "collaborators" edges to the CollectionCollaborator entity.
func (_u *CollectionUpdateOne) AddCollaborators(v ...*CollectionCollaborator) *CollectionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCollaboratorIDs(ids...)
}

// AddFlashcardIDs adds the "flashcards" edge to the Flashcard entity by IDs.
func (_u *CollectionUpdateOne) AddFlashcardIDs(ids ...uuid.UUID) *CollectionUpdateOne {
	_u.mutation.AddFlashcardIDs(ids...)
	return _u
}

// AddFlashcards adds the "flashcards" edges to the Flashcard entity.
func (_u *CollectionUpdateOne) AddFlashcards(v ...*Flashcard) *CollectionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFlashcardIDs(ids...)
}

// Mutation returns the CollectionMutation object of the builder.
func (_u *CollectionUpdateOne) Mutation() *CollectionMutation {
	return _u.mutation
}

// ClearCollaborators clears all "collaborators" edges to the CollectionCollaborator entity.
func (_u *CollectionUpdateOne) ClearCollaborators() *CollectionUpdateOne {
	_u.mutation.ClearCollaborators()
	return _u
}

// RemoveCollaboratorIDs removes the "collaborators" edge to CollectionCollaborator entities by IDs.
func (_u *CollectionUpdateOne) RemoveCollaboratorIDs(ids ...uuid.UUID) *CollectionUpdateOne {
	_u.mutation.RemoveCollaboratorIDs(ids...)
	return _u
}

// RemoveCollaborators removes "collaborators" edges to CollectionCollaborator entities.
func (_u *CollectionUpdateOne) RemoveCollaborators(v ...*CollectionCollaborator) *CollectionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCollaboratorIDs(ids...)
}

// ClearFlashcards clears all "flashcards" edges to the Flashcard entity.
func (_u *CollectionUpdateOne) ClearFlashcards() *CollectionUpdateOne {
	_u.mutation.ClearFlashcards()
	return _u
}

// RemoveFlashcardIDs removes the "flashcards" edge to Flashcard entities by IDs.
func (_u *CollectionUpdateOne) RemoveFlashcardIDs(ids ...uuid.UUID) *CollectionUpdateOne {
	_u.mutation.RemoveFlashcardIDs(ids...)
	return _u
}

// RemoveFlashcards removes "flashcards" edges to Flashcard entities.
func (_u *CollectionUpdateOne) RemoveFlashcards(v ...*Flashcard) *CollectionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFlashcardIDs(ids...)
}

// Where appends a list predicates to the CollectionUpdate builder.
func (_u *CollectionUpdateOne) Where(ps ...predicate.Collection) *CollectionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CollectionUpdateOne) Select(field string, fields ...string) *CollectionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Collection entity.
func (_u *CollectionUpdateOne) Save(ctx context.Context) (*Collection, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CollectionUpdateOne) SaveX(ctx context.Context) *Collection {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CollectionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CollectionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CollectionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := collection.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CollectionUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := collection.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Collection.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OwnerID(); ok {
		if err := collection.OwnerIDValidator(v); err != nil {
			return &ValidationError{Name: "owner_id", err: fmt.Errorf(`ent: validator failed for field "Collection.owner_id": %w`, err)}
		}
	}
	return nil
}

func (_u *CollectionUpdateOne) sqlSave(ctx context.Context) (_node *Collection, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(collection.Table, collection.Columns, sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Collection.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, collection.FieldID)
		for _, f := range fields {
			if !collection.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != collection.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(collection.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(collection.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(collection.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(collection.FieldOwnerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(collection.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(collection.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CollaboratorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.CollaboratorsTable,
			Columns: []string{collection.CollaboratorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collectioncollaborator.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCollaboratorsIDs(); len(nodes) > 0 && !_u.mutation.CollaboratorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.CollaboratorsTable,
			Columns: []string{collection.CollaboratorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collectioncollaborator.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollaboratorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.CollaboratorsTable,
			Columns: []string{collection.CollaboratorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collectioncollaborator.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FlashcardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.FlashcardsTable,
			Columns: []string{collection.FlashcardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flashcard.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFlashcardsIDs(); len(nodes) > 0 && !_u.mutation.FlashcardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.FlashcardsTable,
			Columns: []string{collection.FlashcardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flashcard.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlashcardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   collection.FlashcardsTable,
			Columns: []string{collection.FlashcardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flashcard.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Collection{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{collection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
