// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/quanphung1120/advanced-quiz-be/ent/collection"
	"github.com/quanphung1120/advanced-quiz-be/ent/collectioncollaborator"
)

// CollectionCollaboratorCreate is the builder for creating a CollectionCollaborator entity.
type CollectionCollaboratorCreate struct {
	config
	mutation *CollectionCollaboratorMutation
	hooks    []Hook
}

// SetCollectionID sets the "collection_id" field.
func (_c *CollectionCollaboratorCreate) SetCollectionID(v uuid.UUID) *CollectionCollaboratorCreate {
	_c.mutation.SetCollectionID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CollectionCollaboratorCreate) SetUserID(v string) *CollectionCollaboratorCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *CollectionCollaboratorCreate) SetRole(v string) *CollectionCollaboratorCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *CollectionCollaboratorCreate) SetNillableRole(v *string) *CollectionCollaboratorCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CollectionCollaboratorCreate) SetCreatedAt(v time.Time) *CollectionCollaboratorCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CollectionCollaboratorCreate) SetNillableCreatedAt(v *time.Time) *CollectionCollaboratorCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CollectionCollaboratorCreate) SetID(v uuid.UUID) *CollectionCollaboratorCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CollectionCollaboratorCreate) SetNillableID(v *uuid.UUID) *CollectionCollaboratorCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetCollection sets the "collection" edge to the Collection entity.
func (_c *CollectionCollaboratorCreate) SetCollection(v *Collection) *CollectionCollaboratorCreate {
	return _c.SetCollectionID(v.ID)
}

// Mutation returns the CollectionCollaboratorMutation object of the builder.
func (_c *CollectionCollaboratorCreate) Mutation() *CollectionCollaboratorMutation {
	return _c.mutation
}

// Save creates the CollectionCollaborator in the database.
func (_c *CollectionCollaboratorCreate) Save(ctx context.Context) (*CollectionCollaborator, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CollectionCollaboratorCreate) SaveX(ctx context.Context) *CollectionCollaborator {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CollectionCollaboratorCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CollectionCollaboratorCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CollectionCollaboratorCreate) defaults() {
	if _, ok := _c.mutation.Role(); !ok {
		v := collectioncollaborator.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := collectioncollaborator.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := collectioncollaborator.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CollectionCollaboratorCreate) check() error {
	if _, ok := _c.mutation.CollectionID(); !ok {
		return &ValidationError{Name: "collection_id", err: errors.New(`ent: missing required field "CollectionCollaborator.collection_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CollectionCollaborator.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := collectioncollaborator.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "CollectionCollaborator.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "CollectionCollaborator.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := collectioncollaborator.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "CollectionCollaborator.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CollectionCollaborator.created_at"`)}
	}
	if len(_c.mutation.CollectionIDs()) == 0 {
		return &ValidationError{Name: "collection", err: errors.New(`ent: missing required edge "CollectionCollaborator.collection"`)}
	}
	return nil
}

func (_c *CollectionCollaboratorCreate) sqlSave(ctx context.Context) (*CollectionCollaborator, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CollectionCollaboratorCreate) createSpec() (*CollectionCollaborator, *sqlgraph.CreateSpec) {
	var (
		_node = &CollectionCollaborator{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(collectioncollaborator.Table, sqlgraph.NewFieldSpec(collectioncollaborator.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(collectioncollaborator.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(collectioncollaborator.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(collectioncollaborator.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.CollectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   collectioncollaborator.CollectionTable,
			Columns: []string{collectioncollaborator.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CollectionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CollectionCollaboratorCreateBulk is the builder for creating many CollectionCollaborator entities in bulk.
type CollectionCollaboratorCreateBulk struct {
	config
	err      error
	builders []*CollectionCollaboratorCreate
}

// Save creates the CollectionCollaborator entities in the database.
func (_c *CollectionCollaboratorCreateBulk) Save(ctx context.Context) ([]*CollectionCollaborator, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CollectionCollaborator, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CollectionCollaboratorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CollectionCollaboratorCreateBulk) SaveX(ctx context.Context) []*CollectionCollaborator {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CollectionCollaboratorCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CollectionCollaboratorCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
