// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/quanphung1120/advanced-quiz-be/ent/collectioncollaborator"
	"github.com/quanphung1120/advanced-quiz-be/ent/predicate"
)

// CollectionCollaboratorDelete is the builder for deleting a CollectionCollaborator entity.
type CollectionCollaboratorDelete struct {
	config
	hooks    []Hook
	mutation *CollectionCollaboratorMutation
}

// Where appends a list predicates to the CollectionCollaboratorDelete builder.
func (_d *CollectionCollaboratorDelete) Where(ps ...predicate.CollectionCollaborator) *CollectionCollaboratorDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CollectionCollaboratorDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CollectionCollaboratorDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CollectionCollaboratorDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(collectioncollaborator.Table, sqlgraph.NewFieldSpec(collectioncollaborator.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CollectionCollaboratorDeleteOne is the builder for deleting a single CollectionCollaborator entity.
type CollectionCollaboratorDeleteOne struct {
	_d *CollectionCollaboratorDelete
}

// Where appends a list predicates to the CollectionCollaboratorDelete builder.
func (_d *CollectionCollaboratorDeleteOne) Where(ps ...predicate.CollectionCollaborator) *CollectionCollaboratorDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CollectionCollaboratorDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{collectioncollaborator.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CollectionCollaboratorDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
