// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/quanphung1120/advanced-quiz-be/ent/collection"
	"github.com/quanphung1120/advanced-quiz-be/ent/collectioncollaborator"
	"github.com/quanphung1120/advanced-quiz-be/ent/predicate"
)

// CollectionCollaboratorUpdate is the builder for updating CollectionCollaborator entities.
type CollectionCollaboratorUpdate struct {
	config
	hooks    []Hook
	mutation *CollectionCollaboratorMutation
}

// Where appends a list predicates to the CollectionCollaboratorUpdate builder.
func (_u *CollectionCollaboratorUpdate) Where(ps ...predicate.CollectionCollaborator) *CollectionCollaboratorUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCollectionID sets the "collection_id" field.
func (_u *CollectionCollaboratorUpdate) SetCollectionID(v uuid.UUID) *CollectionCollaboratorUpdate {
	_u.mutation.SetCollectionID(v)
	return _u
}

// SetNillableCollectionID sets the "collection_id" field if the given value is not nil.
func (_u *CollectionCollaboratorUpdate) SetNillableCollectionID(v *uuid.UUID) *CollectionCollaboratorUpdate {
	if v != nil {
		_u.SetCollectionID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CollectionCollaboratorUpdate) SetUserID(v string) *CollectionCollaboratorUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CollectionCollaboratorUpdate) SetNillableUserID(v *string) *CollectionCollaboratorUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *CollectionCollaboratorUpdate) SetRole(v string) *CollectionCollaboratorUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *CollectionCollaboratorUpdate) SetNillableRole(v *string) *CollectionCollaboratorUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetCollection sets the "collection" edge to the Collection entity.
func (_u *CollectionCollaboratorUpdate) SetCollection(v *Collection) *CollectionCollaboratorUpdate {
	return _u.SetCollectionID(v.ID)
}

// Mutation returns the CollectionCollaboratorMutation object of the builder.
func (_u *CollectionCollaboratorUpdate) Mutation() *CollectionCollaboratorMutation {
	return _u.mutation
}

// ClearCollection clears the "collection" edge to the Collection entity.
func (_u *CollectionCollaboratorUpdate) ClearCollection() *CollectionCollaboratorUpdate {
	_u.mutation.ClearCollection()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CollectionCollaboratorUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CollectionCollaboratorUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CollectionCollaboratorUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CollectionCollaboratorUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CollectionCollaboratorUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := collectioncollaborator.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "CollectionCollaborator.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := collectioncollaborator.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "CollectionCollaborator.role": %w`, err)}
		}
	}
	if _u.mutation.CollectionCleared() && len(_u.mutation.CollectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CollectionCollaborator.collection"`)
	}
	return nil
}

func (_u *CollectionCollaboratorUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(collectioncollaborator.Table, collectioncollaborator.Columns, sqlgraph.NewFieldSpec(collectioncollaborator.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(collectioncollaborator.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(collectioncollaborator.FieldRole, field.TypeString, value)
	}
	if _u.mutation.CollectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   collectioncollaborator.CollectionTable,
			Columns: []string{collectioncollaborator.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   collectioncollaborator.CollectionTable,
			Columns: []string{collectioncollaborator.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{collectioncollaborator.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CollectionCollaboratorUpdateOne is the builder for updating a single CollectionCollaborator entity.
type CollectionCollaboratorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CollectionCollaboratorMutation
}

// SetCollectionID sets the "collection_id" field.
func (_u *CollectionCollaboratorUpdateOne) SetCollectionID(v uuid.UUID) *CollectionCollaboratorUpdateOne {
	_u.mutation.SetCollectionID(v)
	return _u
}

// SetNillableCollectionID sets the "collection_id" field if the given value is not nil.
func (_u *CollectionCollaboratorUpdateOne) SetNillableCollectionID(v *uuid.UUID) *CollectionCollaboratorUpdateOne {
	if v != nil {
		_u.SetCollectionID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CollectionCollaboratorUpdateOne) SetUserID(v string) *CollectionCollaboratorUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CollectionCollaboratorUpdateOne) SetNillableUserID(v *string) *CollectionCollaboratorUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *CollectionCollaboratorUpdateOne) SetRole(v string) *CollectionCollaboratorUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *CollectionCollaboratorUpdateOne) SetNillableRole(v *string) *CollectionCollaboratorUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetCollection sets the "collection" edge to the Collection entity.
func (_u *CollectionCollaboratorUpdateOne) SetCollection(v *Collection) *CollectionCollaboratorUpdateOne {
	return _u.SetCollectionID(v.ID)
}

// Mutation returns the CollectionCollaboratorMutation object of the builder.
func (_u *CollectionCollaboratorUpdateOne) Mutation() *CollectionCollaboratorMutation {
	return _u.mutation
}

// ClearCollection clears the "collection" edge to the Collection entity.
func (_u *CollectionCollaboratorUpdateOne) ClearCollection() *CollectionCollaboratorUpdateOne {
	_u.mutation.ClearCollection()
	return _u
}

// Where appends a list predicates to the CollectionCollaboratorUpdate builder.
func (_u *CollectionCollaboratorUpdateOne) Where(ps ...predicate.CollectionCollaborator) *CollectionCollaboratorUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CollectionCollaboratorUpdateOne) Select(field string, fields ...string) *CollectionCollaboratorUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CollectionCollaborator entity.
func (_u *CollectionCollaboratorUpdateOne) Save(ctx context.Context) (*CollectionCollaborator, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CollectionCollaboratorUpdateOne) SaveX(ctx context.Context) *CollectionCollaborator {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CollectionCollaboratorUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CollectionCollaboratorUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CollectionCollaboratorUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := collectioncollaborator.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "CollectionCollaborator.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := collectioncollaborator.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "CollectionCollaborator.role": %w`, err)}
		}
	}
	if _u.mutation.CollectionCleared() && len(_u.mutation.CollectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CollectionCollaborator.collection"`)
	}
	return nil
}

func (_u *CollectionCollaboratorUpdateOne) sqlSave(ctx context.Context) (_node *CollectionCollaborator, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(collectioncollaborator.Table, collectioncollaborator.Columns, sqlgraph.NewFieldSpec(collectioncollaborator.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CollectionCollaborator.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, collectioncollaborator.FieldID)
		for _, f := range fields {
			if !collectioncollaborator.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != collectioncollaborator.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(collectioncollaborator.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(collectioncollaborator.FieldRole, field.TypeString, value)
	}
	if _u.mutation.CollectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   collectioncollaborator.CollectionTable,
			Columns: []string{collectioncollaborator.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   collectioncollaborator.CollectionTable,
			Columns: []string{collectioncollaborator.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CollectionCollaborator{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{collectioncollaborator.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
