// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/quanphung1120/advanced-quiz-be/ent/flashcard"
	"github.com/quanphung1120/advanced-quiz-be/ent/flashcardreview"
	"github.com/quanphung1120/advanced-quiz-be/ent/predicate"
)

// FlashcardReviewUpdate is the builder for updating FlashcardReview entities.
type FlashcardReviewUpdate struct {
	config
	hooks    []Hook
	mutation *FlashcardReviewMutation
}

// Where appends a list predicates to the FlashcardReviewUpdate builder.
func (_u *FlashcardReviewUpdate) Where(ps ...predicate.FlashcardReview) *FlashcardReviewUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *FlashcardReviewUpdate) SetUserID(v string) *FlashcardReviewUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *FlashcardReviewUpdate) SetNillableUserID(v *string) *FlashcardReviewUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetFlashcardID sets the "flashcard_id" field.
func (_u *FlashcardReviewUpdate) SetFlashcardID(v uuid.UUID) *FlashcardReviewUpdate {
	_u.mutation.SetFlashcardID(v)
	return _u
}

// SetNillableFlashcardID sets the "flashcard_id" field if the given value is not nil.
func (_u *FlashcardReviewUpdate) SetNillableFlashcardID(v *uuid.UUID) *FlashcardReviewUpdate {
	if v != nil {
		_u.SetFlashcardID(*v)
	}
	return _u
}

// SetEaseFactor sets the "ease_factor" field.
func (_u *FlashcardReviewUpdate) SetEaseFactor(v float64) *FlashcardReviewUpdate {
	_u.mutation.ResetEaseFactor()
	_u.mutation.SetEaseFactor(v)
	return _u
}

// SetNillableEaseFactor sets the "ease_factor" field if the given value is not nil.
func (_u *FlashcardReviewUpdate) SetNillableEaseFactor(v *float64) *FlashcardReviewUpdate {
	if v != nil {
		_u.SetEaseFactor(*v)
	}
	return _u
}

// AddEaseFactor adds value to the "ease_factor" field.
func (_u *FlashcardReviewUpdate) AddEaseFactor(v float64) *FlashcardReviewUpdate {
	_u.mutation.AddEaseFactor(v)
	return _u
}

// SetInterval sets the "interval" field.
func (_u *FlashcardReviewUpdate) SetInterval(v int) *FlashcardReviewUpdate {
	_u.mutation.ResetInterval()
	_u.mutation.SetInterval(v)
	return _u
}

// SetNillableInterval sets the "interval" field if the given value is not nil.
func (_u *FlashcardReviewUpdate) SetNillableInterval(v *int) *FlashcardReviewUpdate {
	if v != nil {
		_u.SetInterval(*v)
	}
	return _u
}

// AddInterval adds value to the "interval" field.
func (_u *FlashcardReviewUpdate) AddInterval(v int) *FlashcardReviewUpdate {
	_u.mutation.AddInterval(v)
	return _u
}

// SetDueAt sets the "due_at" field.
func (_u *FlashcardReviewUpdate) SetDueAt(v time.Time) *FlashcardReviewUpdate {
	_u.mutation.SetDueAt(v)
	return _u
}

// SetNillableDueAt sets the "due_at" field if the given value is not nil.
func (_u *FlashcardReviewUpdate) SetNillableDueAt(v *time.Time) *FlashcardReviewUpdate {
	if v != nil {
		_u.SetDueAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *FlashcardReviewUpdate) SetStatus(v flashcardreview.Status) *FlashcardReviewUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FlashcardReviewUpdate) SetNillableStatus(v *flashcardreview.Status) *FlashcardReviewUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLearningStep sets the "learning_step" field.
func (_u *FlashcardReviewUpdate) SetLearningStep(v int) *FlashcardReviewUpdate {
	_u.mutation.ResetLearningStep()
	_u.mutation.SetLearningStep(v)
	return _u
}

// SetNillableLearningStep sets the "learning_step" field if the given value is not nil.
func (_u *FlashcardReviewUpdate) SetNillableLearningStep(v *int) *FlashcardReviewUpdate {
	if v != nil {
		_u.SetLearningStep(*v)
	}
	return _u
}

// AddLearningStep adds value to the "learning_step" field.
func (_u *FlashcardReviewUpdate) AddLearningStep(v int) *FlashcardReviewUpdate {
	_u.mutation.AddLearningStep(v)
	return _u
}

// SetReviewCount sets the "review_count" field.
func (_u *FlashcardReviewUpdate) SetReviewCount(v int) *FlashcardReviewUpdate {
	_u.mutation.ResetReviewCount()
	_u.mutation.SetReviewCount(v)
	return _u
}

// SetNillableReviewCount sets the "review_count" field if the given value is not nil.
func (_u *FlashcardReviewUpdate) SetNillableReviewCount(v *int) *FlashcardReviewUpdate {
	if v != nil {
		_u.SetReviewCount(*v)
	}
	return _u
}

// AddReviewCount adds value to the "review_count" field.
func (_u *FlashcardReviewUpdate) AddReviewCount(v int) *FlashcardReviewUpdate {
	_u.mutation.AddReviewCount(v)
	return _u
}

// SetLapseCount sets the "lapse_count" field.
func (_u *FlashcardReviewUpdate) SetLapseCount(v int) *FlashcardReviewUpdate {
	_u.mutation.ResetLapseCount()
	_u.mutation.SetLapseCount(v)
	return _u
}

// SetNillableLapseCount sets the "lapse_count" field if the given value is not nil.
func (_u *FlashcardReviewUpdate) SetNillableLapseCount(v *int) *FlashcardReviewUpdate {
	if v != nil {
		_u.SetLapseCount(*v)
	}
	return _u
}

// AddLapseCount adds value to the "lapse_count" field.
func (_u *FlashcardReviewUpdate) AddLapseCount(v int) *FlashcardReviewUpdate {
	_u.mutation.AddLapseCount(v)
	return _u
}

// SetLastReviewedAt sets the "last_reviewed_at" field.
func (_u *FlashcardReviewUpdate) SetLastReviewedAt(v time.Time) *FlashcardReviewUpdate {
	_u.mutation.SetLastReviewedAt(v)
	return _u
}

// SetNillableLastReviewedAt sets the "last_reviewed_at" field if the given value is not nil.
func (_u *FlashcardReviewUpdate) SetNillableLastReviewedAt(v *time.Time) *FlashcardReviewUpdate {
	if v != nil {
		_u.SetLastReviewedAt(*v)
	}
	return _u
}

// ClearLastReviewedAt clears the value of the "last_reviewed_at" field.
func (_u *FlashcardReviewUpdate) ClearLastReviewedAt() *FlashcardReviewUpdate {
	_u.mutation.ClearLastReviewedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FlashcardReviewUpdate) SetUpdatedAt(v time.Time) *FlashcardReviewUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFlashcard sets the "flashcard" edge to the Flashcard entity.
func (_u *FlashcardReviewUpdate) SetFlashcard(v *Flashcard) *FlashcardReviewUpdate {
	return _u.SetFlashcardID(v.ID)
}

// Mutation returns the FlashcardReviewMutation object of the builder.
func (_u *FlashcardReviewUpdate) Mutation() *FlashcardReviewMutation {
	return _u.mutation
}

// ClearFlashcard clears the "flashcard" edge to the Flashcard entity.
func (_u *FlashcardReviewUpdate) ClearFlashcard() *FlashcardReviewUpdate {
	_u.mutation.ClearFlashcard()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FlashcardReviewUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FlashcardReviewUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FlashcardReviewUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FlashcardReviewUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FlashcardReviewUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := flashcardreview.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FlashcardReviewUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := flashcardreview.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "FlashcardReview.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EaseFactor(); ok {
		if err := flashcardreview.EaseFactorValidator(v); err != nil {
			return &ValidationError{Name: "ease_factor", err: fmt.Errorf(`ent: validator failed for field "FlashcardReview.ease_factor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Interval(); ok {
		if err := flashcardreview.IntervalValidator(v); err != nil {
			return &ValidationError{Name: "interval", err: fmt.Errorf(`ent: validator failed for field "FlashcardReview.interval": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := flashcardreview.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FlashcardReview.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LearningStep(); ok {
		if err := flashcardreview.LearningStepValidator(v); err != nil {
			return &ValidationError{Name: "learning_step", err: fmt.Errorf(`ent: validator failed for field "FlashcardReview.learning_step": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReviewCount(); ok {
		if err := flashcardreview.ReviewCountValidator(v); err != nil {
			return &ValidationError{Name: "review_count", err: fmt.Errorf(`ent: validator failed for field "FlashcardReview.review_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LapseCount(); ok {
		if err := flashcardreview.LapseCountValidator(v); err != nil {
			return &ValidationError{Name: "lapse_count", err: fmt.Errorf(`ent: validator failed for field "FlashcardReview.lapse_count": %w`, err)}
		}
	}
	if _u.mutation.FlashcardCleared() && len(_u.mutation.FlashcardIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FlashcardReview.flashcard"`)
	}
	return nil
}

func (_u *FlashcardReviewUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(flashcardreview.Table, flashcardreview.Columns, sqlgraph.NewFieldSpec(flashcardreview.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(flashcardreview.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EaseFactor(); ok {
		_spec.SetField(flashcardreview.FieldEaseFactor, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEaseFactor(); ok {
		_spec.AddField(flashcardreview.FieldEaseFactor, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Interval(); ok {
		_spec.SetField(flashcardreview.FieldInterval, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInterval(); ok {
		_spec.AddField(flashcardreview.FieldInterval, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DueAt(); ok {
		_spec.SetField(flashcardreview.FieldDueAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(flashcardreview.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LearningStep(); ok {
		_spec.SetField(flashcardreview.FieldLearningStep, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLearningStep(); ok {
		_spec.AddField(flashcardreview.FieldLearningStep, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReviewCount(); ok {
		_spec.SetField(flashcardreview.FieldReviewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReviewCount(); ok {
		_spec.AddField(flashcardreview.FieldReviewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LapseCount(); ok {
		_spec.SetField(flashcardreview.FieldLapseCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLapseCount(); ok {
		_spec.AddField(flashcardreview.FieldLapseCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastReviewedAt(); ok {
		_spec.SetField(flashcardreview.FieldLastReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.LastReviewedAtCleared() {
		_spec.ClearField(flashcardreview.FieldLastReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(flashcardreview.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.FlashcardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flashcardreview.FlashcardTable,
			Columns: []string{flashcardreview.FlashcardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flashcard.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlashcardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flashcardreview.FlashcardTable,
			Columns: []string{flashcardreview.FlashcardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flashcard.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flashcardreview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FlashcardReviewUpdateOne is the builder for updating a single FlashcardReview entity.
type FlashcardReviewUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FlashcardReviewMutation
}

// SetUserID sets the "user_id" field.
func (_u *FlashcardReviewUpdateOne) SetUserID(v string) *FlashcardReviewUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *FlashcardReviewUpdateOne) SetNillableUserID(v *string) *FlashcardReviewUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetFlashcardID sets the "flashcard_id" field.
func (_u *FlashcardReviewUpdateOne) SetFlashcardID(v uuid.UUID) *FlashcardReviewUpdateOne {
	_u.mutation.SetFlashcardID(v)
	return _u
}

// SetNillableFlashcardID sets the "flashcard_id" field if the given value is not nil.
func (_u *FlashcardReviewUpdateOne) SetNillableFlashcardID(v *uuid.UUID) *FlashcardReviewUpdateOne {
	if v != nil {
		_u.SetFlashcardID(*v)
	}
	return _u
}

// SetEaseFactor sets the "ease_factor" field.
func (_u *FlashcardReviewUpdateOne) SetEaseFactor(v float64) *FlashcardReviewUpdateOne {
	_u.mutation.ResetEaseFactor()
	_u.mutation.SetEaseFactor(v)
	return _u
}

// SetNillableEaseFactor sets the "ease_factor" field if the given value is not nil.
func (_u *FlashcardReviewUpdateOne) SetNillableEaseFactor(v *float64) *FlashcardReviewUpdateOne {
	if v != nil {
		_u.SetEaseFactor(*v)
	}
	return _u
}

// AddEaseFactor adds value to the "ease_factor" field.
func (_u *FlashcardReviewUpdateOne) AddEaseFactor(v float64) *FlashcardReviewUpdateOne {
	_u.mutation.AddEaseFactor(v)
	return _u
}

// SetInterval sets the "interval" field.
func (_u *FlashcardReviewUpdateOne) SetInterval(v int) *FlashcardReviewUpdateOne {
	_u.mutation.ResetInterval()
	_u.mutation.SetInterval(v)
	return _u
}

// SetNillableInterval sets the "interval" field if the given value is not nil.
func (_u *FlashcardReviewUpdateOne) SetNillableInterval(v *int) *FlashcardReviewUpdateOne {
	if v != nil {
		_u.SetInterval(*v)
	}
	return _u
}

// AddInterval adds value to the "interval" field.
func (_u *FlashcardReviewUpdateOne) AddInterval(v int) *FlashcardReviewUpdateOne {
	_u.mutation.AddInterval(v)
	return _u
}

// SetDueAt sets the "due_at" field.
func (_u *FlashcardReviewUpdateOne) SetDueAt(v time.Time) *FlashcardReviewUpdateOne {
	_u.mutation.SetDueAt(v)
	return _u
}

// SetNillableDueAt sets the "due_at" field if the given value is not nil.
func (_u *FlashcardReviewUpdateOne) SetNillableDueAt(v *time.Time) *FlashcardReviewUpdateOne {
	if v != nil {
		_u.SetDueAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *FlashcardReviewUpdateOne) SetStatus(v flashcardreview.Status) *FlashcardReviewUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FlashcardReviewUpdateOne) SetNillableStatus(v *flashcardreview.Status) *FlashcardReviewUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLearningStep sets the "learning_step" field.
func (_u *FlashcardReviewUpdateOne) SetLearningStep(v int) *FlashcardReviewUpdateOne {
	_u.mutation.ResetLearningStep()
	_u.mutation.SetLearningStep(v)
	return _u
}

// SetNillableLearningStep sets the "learning_step" field if the given value is not nil.
func (_u *FlashcardReviewUpdateOne) SetNillableLearningStep(v *int) *FlashcardReviewUpdateOne {
	if v != nil {
		_u.SetLearningStep(*v)
	}
	return _u
}

// AddLearningStep adds value to the "learning_step" field.
func (_u *FlashcardReviewUpdateOne) AddLearningStep(v int) *FlashcardReviewUpdateOne {
	_u.mutation.AddLearningStep(v)
	return _u
}

// SetReviewCount sets the "review_count" field.
func (_u *FlashcardReviewUpdateOne) SetReviewCount(v int) *FlashcardReviewUpdateOne {
	_u.mutation.ResetReviewCount()
	_u.mutation.SetReviewCount(v)
	return _u
}

// SetNillableReviewCount sets the "review_count" field if the given value is not nil.
func (_u *FlashcardReviewUpdateOne) SetNillableReviewCount(v *int) *FlashcardReviewUpdateOne {
	if v != nil {
		_u.SetReviewCount(*v)
	}
	return _u
}

// AddReviewCount adds value to the "review_count" field.
func (_u *FlashcardReviewUpdateOne) AddReviewCount(v int) *FlashcardReviewUpdateOne {
	_u.mutation.AddReviewCount(v)
	return _u
}

// SetLapseCount sets the "lapse_count" field.
func (_u *FlashcardReviewUpdateOne) SetLapseCount(v int) *FlashcardReviewUpdateOne {
	_u.mutation.ResetLapseCount()
	_u.mutation.SetLapseCount(v)
	return _u
}

// SetNillableLapseCount sets the "lapse_count" field if the given value is not nil.
func (_u *FlashcardReviewUpdateOne) SetNillableLapseCount(v *int) *FlashcardReviewUpdateOne {
	if v != nil {
		_u.SetLapseCount(*v)
	}
	return _u
}

// AddLapseCount adds value to the "lapse_count" field.
func (_u *FlashcardReviewUpdateOne) AddLapseCount(v int) *FlashcardReviewUpdateOne {
	_u.mutation.AddLapseCount(v)
	return _u
}

// SetLastReviewedAt sets the "last_reviewed_at" field.
func (_u *FlashcardReviewUpdateOne) SetLastReviewedAt(v time.Time) *FlashcardReviewUpdateOne {
	_u.mutation.SetLastReviewedAt(v)
	return _u
}

// SetNillableLastReviewedAt sets the "last_reviewed_at" field if the given value is not nil.
func (_u *FlashcardReviewUpdateOne) SetNillableLastReviewedAt(v *time.Time) *FlashcardReviewUpdateOne {
	if v != nil {
		_u.SetLastReviewedAt(*v)
	}
	return _u
}

// ClearLastReviewedAt clears the value of the "last_reviewed_at" field.
func (_u *FlashcardReviewUpdateOne) ClearLastReviewedAt() *FlashcardReviewUpdateOne {
	_u.mutation.ClearLastReviewedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FlashcardReviewUpdateOne) SetUpdatedAt(v time.Time) *FlashcardReviewUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFlashcard sets the "flashcard" edge to the Flashcard entity.
func (_u *FlashcardReviewUpdateOne) SetFlashcard(v *Flashcard) *FlashcardReviewUpdateOne {
	return _u.SetFlashcardID(v.ID)
}

// Mutation returns the FlashcardReviewMutation object of the builder.
func (_u *FlashcardReviewUpdateOne) Mutation() *FlashcardReviewMutation {
	return _u.mutation
}

// ClearFlashcard clears the "flashcard" edge to the Flashcard entity.
func (_u *FlashcardReviewUpdateOne) ClearFlashcard() *FlashcardReviewUpdateOne {
	_u.mutation.ClearFlashcard()
	return _u
}

// Where appends a list predicates to the FlashcardReviewUpdate builder.
func (_u *FlashcardReviewUpdateOne) Where(ps ...predicate.FlashcardReview) *FlashcardReviewUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FlashcardReviewUpdateOne) Select(field string, fields ...string) *FlashcardReviewUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FlashcardReview entity.
func (_u *FlashcardReviewUpdateOne) Save(ctx context.Context) (*FlashcardReview, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FlashcardReviewUpdateOne) SaveX(ctx context.Context) *FlashcardReview {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FlashcardReviewUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FlashcardReviewUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FlashcardReviewUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := flashcardreview.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FlashcardReviewUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := flashcardreview.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "FlashcardReview.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EaseFactor(); ok {
		if err := flashcardreview.EaseFactorValidator(v); err != nil {
			return &ValidationError{Name: "ease_factor", err: fmt.Errorf(`ent: validator failed for field "FlashcardReview.ease_factor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Interval(); ok {
		if err := flashcardreview.IntervalValidator(v); err != nil {
			return &ValidationError{Name: "interval", err: fmt.Errorf(`ent: validator failed for field "FlashcardReview.interval": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := flashcardreview.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FlashcardReview.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LearningStep(); ok {
		if err := flashcardreview.LearningStepValidator(v); err != nil {
			return &ValidationError{Name: "learning_step", err: fmt.Errorf(`ent: validator failed for field "FlashcardReview.learning_step": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReviewCount(); ok {
		if err := flashcardreview.ReviewCountValidator(v); err != nil {
			return &ValidationError{Name: "review_count", err: fmt.Errorf(`ent: validator failed for field "FlashcardReview.review_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LapseCount(); ok {
		if err := flashcardreview.LapseCountValidator(v); err != nil {
			return &ValidationError{Name: "lapse_count", err: fmt.Errorf(`ent: validator failed for field "FlashcardReview.lapse_count": %w`, err)}
		}
	}
	if _u.mutation.FlashcardCleared() && len(_u.mutation.FlashcardIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FlashcardReview.flashcard"`)
	}
	return nil
}

func (_u *FlashcardReviewUpdateOne) sqlSave(ctx context.Context) (_node *FlashcardReview, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(flashcardreview.Table, flashcardreview.Columns, sqlgraph.NewFieldSpec(flashcardreview.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FlashcardReview.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, flashcardreview.FieldID)
		for _, f := range fields {
			if !flashcardreview.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != flashcardreview.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(flashcardreview.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EaseFactor(); ok {
		_spec.SetField(flashcardreview.FieldEaseFactor, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEaseFactor(); ok {
		_spec.AddField(flashcardreview.FieldEaseFactor, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Interval(); ok {
		_spec.SetField(flashcardreview.FieldInterval, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInterval(); ok {
		_spec.AddField(flashcardreview.FieldInterval, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DueAt(); ok {
		_spec.SetField(flashcardreview.FieldDueAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(flashcardreview.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LearningStep(); ok {
		_spec.SetField(flashcardreview.FieldLearningStep, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLearningStep(); ok {
		_spec.AddField(flashcardreview.FieldLearningStep, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReviewCount(); ok {
		_spec.SetField(flashcardreview.FieldReviewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReviewCount(); ok {
		_spec.AddField(flashcardreview.FieldReviewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LapseCount(); ok {
		_spec.SetField(flashcardreview.FieldLapseCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLapseCount(); ok {
		_spec.AddField(flashcardreview.FieldLapseCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastReviewedAt(); ok {
		_spec.SetField(flashcardreview.FieldLastReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.LastReviewedAtCleared() {
		_spec.ClearField(flashcardreview.FieldLastReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(flashcardreview.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.FlashcardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flashcardreview.FlashcardTable,
			Columns: []string{flashcardreview.FlashcardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flashcard.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FlashcardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flashcardreview.FlashcardTable,
			Columns: []string{flashcardreview.FlashcardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flashcard.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FlashcardReview{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flashcardreview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
