// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/quanphung1120/advanced-quiz-be/ent/flashcard"
	"github.com/quanphung1120/advanced-quiz-be/ent/flashcardreview"
)

// FlashcardReviewCreate is the builder for creating a FlashcardReview entity.
type FlashcardReviewCreate struct {
	config
	mutation *FlashcardReviewMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *FlashcardReviewCreate) SetUserID(v string) *FlashcardReviewCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetFlashcardID sets the "flashcard_id" field.
func (_c *FlashcardReviewCreate) SetFlashcardID(v uuid.UUID) *FlashcardReviewCreate {
	_c.mutation.SetFlashcardID(v)
	return _c
}

// SetEaseFactor sets the "ease_factor" field.
func (_c *FlashcardReviewCreate) SetEaseFactor(v float64) *FlashcardReviewCreate {
	_c.mutation.SetEaseFactor(v)
	return _c
}

// SetNillableEaseFactor sets the "ease_factor" field if the given value is not nil.
func (_c *FlashcardReviewCreate) SetNillableEaseFactor(v *float64) *FlashcardReviewCreate {
	if v != nil {
		_c.SetEaseFactor(*v)
	}
	return _c
}

// SetInterval sets the "interval" field.
func (_c *FlashcardReviewCreate) SetInterval(v int) *FlashcardReviewCreate {
	_c.mutation.SetInterval(v)
	return _c
}

// SetNillableInterval sets the "interval" field if the given value is not nil.
func (_c *FlashcardReviewCreate) SetNillableInterval(v *int) *FlashcardReviewCreate {
	if v != nil {
		_c.SetInterval(*v)
	}
	return _c
}

// SetDueAt sets the "due_at" field.
func (_c *FlashcardReviewCreate) SetDueAt(v time.Time) *FlashcardReviewCreate {
	_c.mutation.SetDueAt(v)
	return _c
}

// SetNillableDueAt sets the "due_at" field if the given value is not nil.
func (_c *FlashcardReviewCreate) SetNillableDueAt(v *time.Time) *FlashcardReviewCreate {
	if v != nil {
		_c.SetDueAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *FlashcardReviewCreate) SetStatus(v flashcardreview.Status) *FlashcardReviewCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *FlashcardReviewCreate) SetNillableStatus(v *flashcardreview.Status) *FlashcardReviewCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLearningStep sets the "learning_step" field.
func (_c *FlashcardReviewCreate) SetLearningStep(v int) *FlashcardReviewCreate {
	_c.mutation.SetLearningStep(v)
	return _c
}

// SetNillableLearningStep sets the "learning_step" field if the given value is not nil.
func (_c *FlashcardReviewCreate) SetNillableLearningStep(v *int) *FlashcardReviewCreate {
	if v != nil {
		_c.SetLearningStep(*v)
	}
	return _c
}

// SetReviewCount sets the "review_count" field.
func (_c *FlashcardReviewCreate) SetReviewCount(v int) *FlashcardReviewCreate {
	_c.mutation.SetReviewCount(v)
	return _c
}

// SetNillableReviewCount sets the "review_count" field if the given value is not nil.
func (_c *FlashcardReviewCreate) SetNillableReviewCount(v *int) *FlashcardReviewCreate {
	if v != nil {
		_c.SetReviewCount(*v)
	}
	return _c
}

// SetLapseCount sets the "lapse_count" field.
func (_c *FlashcardReviewCreate) SetLapseCount(v int) *FlashcardReviewCreate {
	_c.mutation.SetLapseCount(v)
	return _c
}

// SetNillableLapseCount sets the "lapse_count" field if the given value is not nil.
func (_c *FlashcardReviewCreate) SetNillableLapseCount(v *int) *FlashcardReviewCreate {
	if v != nil {
		_c.SetLapseCount(*v)
	}
	return _c
}

// SetLastReviewedAt sets the "last_reviewed_at" field.
func (_c *FlashcardReviewCreate) SetLastReviewedAt(v time.Time) *FlashcardReviewCreate {
	_c.mutation.SetLastReviewedAt(v)
	return _c
}

// SetNillableLastReviewedAt sets the "last_reviewed_at" field if the given value is not nil.
func (_c *FlashcardReviewCreate) SetNillableLastReviewedAt(v *time.Time) *FlashcardReviewCreate {
	if v != nil {
		_c.SetLastReviewedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FlashcardReviewCreate) SetCreatedAt(v time.Time) *FlashcardReviewCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FlashcardReviewCreate) SetNillableCreatedAt(v *time.Time) *FlashcardReviewCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FlashcardReviewCreate) SetUpdatedAt(v time.Time) *FlashcardReviewCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FlashcardReviewCreate) SetNillableUpdatedAt(v *time.Time) *FlashcardReviewCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FlashcardReviewCreate) SetID(v uuid.UUID) *FlashcardReviewCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *FlashcardReviewCreate) SetNillableID(v *uuid.UUID) *FlashcardReviewCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetFlashcard sets the "flashcard" edge to the Flashcard entity.
func (_c *FlashcardReviewCreate) SetFlashcard(v *Flashcard) *FlashcardReviewCreate {
	return _c.SetFlashcardID(v.ID)
}

// Mutation returns the FlashcardReviewMutation object of the builder.
func (_c *FlashcardReviewCreate) Mutation() *FlashcardReviewMutation {
	return _c.mutation
}

// Save creates the FlashcardReview in the database.
func (_c *FlashcardReviewCreate) Save(ctx context.Context) (*FlashcardReview, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FlashcardReviewCreate) SaveX(ctx context.Context) *FlashcardReview {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FlashcardReviewCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FlashcardReviewCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FlashcardReviewCreate) defaults() {
	if _, ok := _c.mutation.EaseFactor(); !ok {
		v := flashcardreview.DefaultEaseFactor
		_c.mutation.SetEaseFactor(v)
	}
	if _, ok := _c.mutation.Interval(); !ok {
		v := flashcardreview.DefaultInterval
		_c.mutation.SetInterval(v)
	}
	if _, ok := _c.mutation.DueAt(); !ok {
		v := flashcardreview.DefaultDueAt()
		_c.mutation.SetDueAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := flashcardreview.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.LearningStep(); !ok {
		v := flashcardreview.DefaultLearningStep
		_c.mutation.SetLearningStep(v)
	}
	if _, ok := _c.mutation.ReviewCount(); !ok {
		v := flashcardreview.DefaultReviewCount
		_c.mutation.SetReviewCount(v)
	}
	if _, ok := _c.mutation.LapseCount(); !ok {
		v := flashcardreview.DefaultLapseCount
		_c.mutation.SetLapseCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := flashcardreview.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := flashcardreview.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := flashcardreview.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FlashcardReviewCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "FlashcardReview.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := flashcardreview.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "FlashcardReview.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FlashcardID(); !ok {
		return &ValidationError{Name: "flashcard_id", err: errors.New(`ent: missing required field "FlashcardReview.flashcard_id"`)}
	}
	if _, ok := _c.mutation.EaseFactor(); !ok {
		return &ValidationError{Name: "ease_factor", err: errors.New(`ent: missing required field "FlashcardReview.ease_factor"`)}
	}
	if v, ok := _c.mutation.EaseFactor(); ok {
		if err := flashcardreview.EaseFactorValidator(v); err != nil {
			return &ValidationError{Name: "ease_factor", err: fmt.Errorf(`ent: validator failed for field "FlashcardReview.ease_factor": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Interval(); !ok {
		return &ValidationError{Name: "interval", err: errors.New(`ent: missing required field "FlashcardReview.interval"`)}
	}
	if v, ok := _c.mutation.Interval(); ok {
		if err := flashcardreview.IntervalValidator(v); err != nil {
			return &ValidationError{Name: "interval", err: fmt.Errorf(`ent: validator failed for field "FlashcardReview.interval": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DueAt(); !ok {
		return &ValidationError{Name: "due_at", err: errors.New(`ent: missing required field "FlashcardReview.due_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "FlashcardReview.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := flashcardreview.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FlashcardReview.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LearningStep(); !ok {
		return &ValidationError{Name: "learning_step", err: errors.New(`ent: missing required field "FlashcardReview.learning_step"`)}
	}
	if v, ok := _c.mutation.LearningStep(); ok {
		if err := flashcardreview.LearningStepValidator(v); err != nil {
			return &ValidationError{Name: "learning_step", err: fmt.Errorf(`ent: validator failed for field "FlashcardReview.learning_step": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReviewCount(); !ok {
		return &ValidationError{Name: "review_count", err: errors.New(`ent: missing required field "FlashcardReview.review_count"`)}
	}
	if v, ok := _c.mutation.ReviewCount(); ok {
		if err := flashcardreview.ReviewCountValidator(v); err != nil {
			return &ValidationError{Name: "review_count", err: fmt.Errorf(`ent: validator failed for field "FlashcardReview.review_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LapseCount(); !ok {
		return &ValidationError{Name: "lapse_count", err: errors.New(`ent: missing required field "FlashcardReview.lapse_count"`)}
	}
	if v, ok := _c.mutation.LapseCount(); ok {
		if err := flashcardreview.LapseCountValidator(v); err != nil {
			return &ValidationError{Name: "lapse_count", err: fmt.Errorf(`ent: validator failed for field "FlashcardReview.lapse_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FlashcardReview.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "FlashcardReview.updated_at"`)}
	}
	if len(_c.mutation.FlashcardIDs()) == 0 {
		return &ValidationError{Name: "flashcard", err: errors.New(`ent: missing required edge "FlashcardReview.flashcard"`)}
	}
	return nil
}

func (_c *FlashcardReviewCreate) sqlSave(ctx context.Context) (*FlashcardReview, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FlashcardReviewCreate) createSpec() (*FlashcardReview, *sqlgraph.CreateSpec) {
	var (
		_node = &FlashcardReview{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(flashcardreview.Table, sqlgraph.NewFieldSpec(flashcardreview.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(flashcardreview.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.EaseFactor(); ok {
		_spec.SetField(flashcardreview.FieldEaseFactor, field.TypeFloat64, value)
		_node.EaseFactor = value
	}
	if value, ok := _c.mutation.Interval(); ok {
		_spec.SetField(flashcardreview.FieldInterval, field.TypeInt, value)
		_node.Interval = value
	}
	if value, ok := _c.mutation.DueAt(); ok {
		_spec.SetField(flashcardreview.FieldDueAt, field.TypeTime, value)
		_node.DueAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(flashcardreview.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LearningStep(); ok {
		_spec.SetField(flashcardreview.FieldLearningStep, field.TypeInt, value)
		_node.LearningStep = value
	}
	if value, ok := _c.mutation.ReviewCount(); ok {
		_spec.SetField(flashcardreview.FieldReviewCount, field.TypeInt, value)
		_node.ReviewCount = value
	}
	if value, ok := _c.mutation.LapseCount(); ok {
		_spec.SetField(flashcardreview.FieldLapseCount, field.TypeInt, value)
		_node.LapseCount = value
	}
	if value, ok := _c.mutation.LastReviewedAt(); ok {
		_spec.SetField(flashcardreview.FieldLastReviewedAt, field.TypeTime, value)
		_node.LastReviewedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(flashcardreview.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(flashcardreview.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.FlashcardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flashcardreview.FlashcardTable,
			Columns: []string{flashcardreview.FlashcardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(flashcard.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FlashcardID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FlashcardReviewCreateBulk is the builder for creating many FlashcardReview entities in bulk.
type FlashcardReviewCreateBulk struct {
	config
	err      error
	builders []*FlashcardReviewCreate
}

// Save creates the FlashcardReview entities in the database.
func (_c *FlashcardReviewCreateBulk) Save(ctx context.Context) ([]*FlashcardReview, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FlashcardReview, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FlashcardReviewMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FlashcardReviewCreateBulk) SaveX(ctx context.Context) []*FlashcardReview {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FlashcardReviewCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FlashcardReviewCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
