// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/quanphung1120/advanced-quiz-be/ent/collection"
	"github.com/quanphung1120/advanced-quiz-be/ent/flashcard"
	"github.com/quanphung1120/advanced-quiz-be/ent/predicate"
)

// FlashcardUpdate is the builder for updating Flashcard entities.
type FlashcardUpdate struct {
	config
	hooks    []Hook
	mutation *FlashcardMutation
}

// Where appends a list predicates to the FlashcardUpdate builder.
func (_u *FlashcardUpdate) Where(ps ...predicate.Flashcard) *FlashcardUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetQuestion sets the "question" field.
func (_u *FlashcardUpdate) SetQuestion(v string) *FlashcardUpdate {
	_u.mutation.SetQuestion(v)
	return _u
}

// SetNillableQuestion sets the "question" field if the given value is not nil.
func (_u *FlashcardUpdate) SetNillableQuestion(v *string) *FlashcardUpdate {
	if v != nil {
		_u.SetQuestion(*v)
	}
	return _u
}

// SetAnswer sets the "answer" field.
func (_u *FlashcardUpdate) SetAnswer(v string) *FlashcardUpdate {
	_u.mutation.SetAnswer(v)
	return _u
}

// SetNillableAnswer sets the "answer" field if the given value is not nil.
func (_u *FlashcardUpdate) SetNillableAnswer(v *string) *FlashcardUpdate {
	if v != nil {
		_u.SetAnswer(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *FlashcardUpdate) SetType(v string) *FlashcardUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *FlashcardUpdate) SetNillableType(v *string) *FlashcardUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetCollectionID sets the "collection_id" field.
func (_u *FlashcardUpdate) SetCollectionID(v uuid.UUID) *FlashcardUpdate {
	_u.mutation.SetCollectionID(v)
	return _u
}

// SetNillableCollectionID sets the "collection_id" field if the given value is not nil.
func (_u *FlashcardUpdate) SetNillableCollectionID(v *uuid.UUID) *FlashcardUpdate {
	if v != nil {
		_u.SetCollectionID(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *FlashcardUpdate) SetCreatedBy(v string) *FlashcardUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *FlashcardUpdate) SetNillableCreatedBy(v *string) *FlashcardUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FlashcardUpdate) SetUpdatedAt(v time.Time) *FlashcardUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCollection sets the "collection" edge to the Collection entity.
func (_u *FlashcardUpdate) SetCollection(v *Collection) *FlashcardUpdate {
	return _u.SetCollectionID(v.ID)
}

// Mutation returns the FlashcardMutation object of the builder.
func (_u *FlashcardUpdate) Mutation() *FlashcardMutation {
	return _u.mutation
}

// ClearCollection clears the "collection" edge to the Collection entity.
func (_u *FlashcardUpdate) ClearCollection() *FlashcardUpdate {
	_u.mutation.ClearCollection()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FlashcardUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FlashcardUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FlashcardUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FlashcardUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FlashcardUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := flashcard.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FlashcardUpdate) check() error {
	if v, ok := _u.mutation.Question(); ok {
		if err := flashcard.QuestionValidator(v); err != nil {
			return &ValidationError{Name: "question", err: fmt.Errorf(`ent: validator failed for field "Flashcard.question": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Answer(); ok {
		if err := flashcard.AnswerValidator(v); err != nil {
			return &ValidationError{Name: "answer", err: fmt.Errorf(`ent: validator failed for field "Flashcard.answer": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := flashcard.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Flashcard.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatedBy(); ok {
		if err := flashcard.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "Flashcard.created_by": %w`, err)}
		}
	}
	if _u.mutation.CollectionCleared() && len(_u.mutation.CollectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Flashcard.collection"`)
	}
	return nil
}

func (_u *FlashcardUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(flashcard.Table, flashcard.Columns, sqlgraph.NewFieldSpec(flashcard.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Question(); ok {
		_spec.SetField(flashcard.FieldQuestion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Answer(); ok {
		_spec.SetField(flashcard.FieldAnswer, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(flashcard.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(flashcard.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(flashcard.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CollectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flashcard.CollectionTable,
			Columns: []string{flashcard.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flashcard.CollectionTable,
			Columns: []string{flashcard.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flashcard.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FlashcardUpdateOne is the builder for updating a single Flashcard entity.
type FlashcardUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FlashcardMutation
}

// SetQuestion sets the "question" field.
func (_u *FlashcardUpdateOne) SetQuestion(v string) *FlashcardUpdateOne {
	_u.mutation.SetQuestion(v)
	return _u
}

// SetNillableQuestion sets the "question" field if the given value is not nil.
func (_u *FlashcardUpdateOne) SetNillableQuestion(v *string) *FlashcardUpdateOne {
	if v != nil {
		_u.SetQuestion(*v)
	}
	return _u
}

// SetAnswer sets the "answer" field.
func (_u *FlashcardUpdateOne) SetAnswer(v string) *FlashcardUpdateOne {
	_u.mutation.SetAnswer(v)
	return _u
}

// SetNillableAnswer sets the "answer" field if the given value is not nil.
func (_u *FlashcardUpdateOne) SetNillableAnswer(v *string) *FlashcardUpdateOne {
	if v != nil {
		_u.SetAnswer(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *FlashcardUpdateOne) SetType(v string) *FlashcardUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *FlashcardUpdateOne) SetNillableType(v *string) *FlashcardUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetCollectionID sets the "collection_id" field.
func (_u *FlashcardUpdateOne) SetCollectionID(v uuid.UUID) *FlashcardUpdateOne {
	_u.mutation.SetCollectionID(v)
	return _u
}

// SetNillableCollectionID sets the "collection_id" field if the given value is not nil.
func (_u *FlashcardUpdateOne) SetNillableCollectionID(v *uuid.UUID) *FlashcardUpdateOne {
	if v != nil {
		_u.SetCollectionID(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *FlashcardUpdateOne) SetCreatedBy(v string) *FlashcardUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *FlashcardUpdateOne) SetNillableCreatedBy(v *string) *FlashcardUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FlashcardUpdateOne) SetUpdatedAt(v time.Time) *FlashcardUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCollection sets the "collection" edge to the Collection entity.
func (_u *FlashcardUpdateOne) SetCollection(v *Collection) *FlashcardUpdateOne {
	return _u.SetCollectionID(v.ID)
}

// Mutation returns the FlashcardMutation object of the builder.
func (_u *FlashcardUpdateOne) Mutation() *FlashcardMutation {
	return _u.mutation
}

// ClearCollection clears the "collection" edge to the Collection entity.
func (_u *FlashcardUpdateOne) ClearCollection() *FlashcardUpdateOne {
	_u.mutation.ClearCollection()
	return _u
}

// Where appends a list predicates to the FlashcardUpdate builder.
func (_u *FlashcardUpdateOne) Where(ps ...predicate.Flashcard) *FlashcardUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FlashcardUpdateOne) Select(field string, fields ...string) *FlashcardUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Flashcard entity.
func (_u *FlashcardUpdateOne) Save(ctx context.Context) (*Flashcard, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FlashcardUpdateOne) SaveX(ctx context.Context) *Flashcard {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FlashcardUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FlashcardUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FlashcardUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := flashcard.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FlashcardUpdateOne) check() error {
	if v, ok := _u.mutation.Question(); ok {
		if err := flashcard.QuestionValidator(v); err != nil {
			return &ValidationError{Name: "question", err: fmt.Errorf(`ent: validator failed for field "Flashcard.question": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Answer(); ok {
		if err := flashcard.AnswerValidator(v); err != nil {
			return &ValidationError{Name: "answer", err: fmt.Errorf(`ent: validator failed for field "Flashcard.answer": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := flashcard.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Flashcard.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatedBy(); ok {
		if err := flashcard.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "Flashcard.created_by": %w`, err)}
		}
	}
	if _u.mutation.CollectionCleared() && len(_u.mutation.CollectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Flashcard.collection"`)
	}
	return nil
}

func (_u *FlashcardUpdateOne) sqlSave(ctx context.Context) (_node *Flashcard, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(flashcard.Table, flashcard.Columns, sqlgraph.NewFieldSpec(flashcard.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Flashcard.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, flashcard.FieldID)
		for _, f := range fields {
			if !flashcard.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != flashcard.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Question(); ok {
		_spec.SetField(flashcard.FieldQuestion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Answer(); ok {
		_spec.SetField(flashcard.FieldAnswer, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(flashcard.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(flashcard.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(flashcard.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CollectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flashcard.CollectionTable,
			Columns: []string{flashcard.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flashcard.CollectionTable,
			Columns: []string{flashcard.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Flashcard{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flashcard.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
