// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/quanphung1120/advanced-quiz-be/ent/collection"
	"github.com/quanphung1120/advanced-quiz-be/ent/flashcard"
)

// Flashcard is the model entity for the Flashcard schema.
type Flashcard struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Question holds the value of the "question" field.
	Question string `json:"question,omitempty"`
	// Answer holds the value of the "answer" field.
	Answer string `json:"answer,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// CollectionID holds the value of the "collection_id" field.
	CollectionID uuid.UUID `json:"collection_id,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FlashcardQuery when eager-loading is set.
	Edges        FlashcardEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FlashcardEdges holds the relations/edges for other nodes in the graph.
type FlashcardEdges struct {
	// Collection holds the value of the collection edge.
	Collection *Collection `json:"collection,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CollectionOrErr returns the Collection value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FlashcardEdges) CollectionOrErr() (*Collection, error) {
	if e.Collection != nil {
		return e.Collection, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: collection.Label}
	}
	return nil, &NotLoadedError{edge: "collection"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Flashcard) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case flashcard.FieldQuestion, flashcard.FieldAnswer, flashcard.FieldType, flashcard.FieldCreatedBy:
			values[i] = new(sql.NullString)
		case flashcard.FieldCreatedAt, flashcard.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case flashcard.FieldID, flashcard.FieldCollectionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Flashcard fields.
func (_m *Flashcard) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case flashcard.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case flashcard.FieldQuestion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field question", values[i])
			} else if value.Valid {
				_m.Question = value.String
			}
		case flashcard.FieldAnswer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field answer", values[i])
			} else if value.Valid {
				_m.Answer = value.String
			}
		case flashcard.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case flashcard.FieldCollectionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field collection_id", values[i])
			} else if value != nil {
				_m.CollectionID = *value
			}
		case flashcard.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case flashcard.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case flashcard.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Flashcard.
// This includes values selected through modifiers, order, etc.
func (_m *Flashcard) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCollection queries the "collection" edge of the Flashcard entity.
func (_m *Flashcard) QueryCollection() *CollectionQuery {
	return NewFlashcardClient(_m.config).QueryCollection(_m)
}

// Update returns a builder for updating this Flashcard.
// Note that you need to call Flashcard.Unwrap() before calling this method if this Flashcard
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Flashcard) Update() *FlashcardUpdateOne {
	return NewFlashcardClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Flashcard entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Flashcard) Unwrap() *Flashcard {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Flashcard is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Flashcard) String() string {
	var builder strings.Builder
	builder.WriteString("Flashcard(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("question=")
	builder.WriteString(_m.Question)
	builder.WriteString(", ")
	builder.WriteString("answer=")
	builder.WriteString(_m.Answer)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("collection_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CollectionID))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Flashcards is a parsable slice of Flashcard.
type Flashcards []*Flashcard
