// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/quanphung1120/advanced-quiz-be/ent/flashcard"
	"github.com/quanphung1120/advanced-quiz-be/ent/flashcardreview"
)

// FlashcardReview is the model entity for the FlashcardReview schema.
type FlashcardReview struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Clerk user ID
	UserID string `json:"user_id,omitempty"`
	// Foreign key to the flashcard being reviewed
	FlashcardID uuid.UUID `json:"flashcard_id,omitempty"`
	// Ease factor (difficulty multiplier), minimum 1.3 like Anki
	EaseFactor float64 `json:"ease_factor,omitempty"`
	// Current interval in minutes (0 means new/learning)
	Interval int `json:"interval,omitempty"`
	// When the card is due for review
	DueAt time.Time `json:"due_at,omitempty"`
	// Current learning status of the card
	Status flashcardreview.Status `json:"status,omitempty"`
	// Current step in learning/relearning phase (0, 1, 2...)
	LearningStep int `json:"learning_step,omitempty"`
	// Total number of reviews completed
	ReviewCount int `json:"review_count,omitempty"`
	// Number of times the card was forgotten (rated 'Again')
	LapseCount int `json:"lapse_count,omitempty"`
	// When the card was last reviewed
	LastReviewedAt *time.Time `json:"last_reviewed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FlashcardReviewQuery when eager-loading is set.
	Edges        FlashcardReviewEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FlashcardReviewEdges holds the relations/edges for other nodes in the graph.
type FlashcardReviewEdges struct {
	// Flashcard holds the value of the flashcard edge.
	Flashcard *Flashcard `json:"flashcard,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// FlashcardOrErr returns the Flashcard value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FlashcardReviewEdges) FlashcardOrErr() (*Flashcard, error) {
	if e.Flashcard != nil {
		return e.Flashcard, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: flashcard.Label}
	}
	return nil, &NotLoadedError{edge: "flashcard"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FlashcardReview) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case flashcardreview.FieldEaseFactor:
			values[i] = new(sql.NullFloat64)
		case flashcardreview.FieldInterval, flashcardreview.FieldLearningStep, flashcardreview.FieldReviewCount, flashcardreview.FieldLapseCount:
			values[i] = new(sql.NullInt64)
		case flashcardreview.FieldUserID, flashcardreview.FieldStatus:
			values[i] = new(sql.NullString)
		case flashcardreview.FieldDueAt, flashcardreview.FieldLastReviewedAt, flashcardreview.FieldCreatedAt, flashcardreview.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case flashcardreview.FieldID, flashcardreview.FieldFlashcardID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FlashcardReview fields.
func (_m *FlashcardReview) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case flashcardreview.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case flashcardreview.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case flashcardreview.FieldFlashcardID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field flashcard_id", values[i])
			} else if value != nil {
				_m.FlashcardID = *value
			}
		case flashcardreview.FieldEaseFactor:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field ease_factor", values[i])
			} else if value.Valid {
				_m.EaseFactor = value.Float64
			}
		case flashcardreview.FieldInterval:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field interval", values[i])
			} else if value.Valid {
				_m.Interval = int(value.Int64)
			}
		case flashcardreview.FieldDueAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field due_at", values[i])
			} else if value.Valid {
				_m.DueAt = value.Time
			}
		case flashcardreview.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = flashcardreview.Status(value.String)
			}
		case flashcardreview.FieldLearningStep:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field learning_step", values[i])
			} else if value.Valid {
				_m.LearningStep = int(value.Int64)
			}
		case flashcardreview.FieldReviewCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field review_count", values[i])
			} else if value.Valid {
				_m.ReviewCount = int(value.Int64)
			}
		case flashcardreview.FieldLapseCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lapse_count", values[i])
			} else if value.Valid {
				_m.LapseCount = int(value.Int64)
			}
		case flashcardreview.FieldLastReviewedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_reviewed_at", values[i])
			} else if value.Valid {
				_m.LastReviewedAt = new(time.Time)
				*_m.LastReviewedAt = value.Time
			}
		case flashcardreview.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case flashcardreview.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FlashcardReview.
// This includes values selected through modifiers, order, etc.
func (_m *FlashcardReview) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryFlashcard queries the "flashcard" edge of the FlashcardReview entity.
func (_m *FlashcardReview) QueryFlashcard() *FlashcardQuery {
	return NewFlashcardReviewClient(_m.config).QueryFlashcard(_m)
}

// Update returns a builder for updating this FlashcardReview.
// Note that you need to call FlashcardReview.Unwrap() before calling this method if this FlashcardReview
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FlashcardReview) Update() *FlashcardReviewUpdateOne {
	return NewFlashcardReviewClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FlashcardReview entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FlashcardReview) Unwrap() *FlashcardReview {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FlashcardReview is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FlashcardReview) String() string {
	var builder strings.Builder
	builder.WriteString("FlashcardReview(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("flashcard_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.FlashcardID))
	builder.WriteString(", ")
	builder.WriteString("ease_factor=")
	builder.WriteString(fmt.Sprintf("%v", _m.EaseFactor))
	builder.WriteString(", ")
	builder.WriteString("interval=")
	builder.WriteString(fmt.Sprintf("%v", _m.Interval))
	builder.WriteString(", ")
	builder.WriteString("due_at=")
	builder.WriteString(_m.DueAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("learning_step=")
	builder.WriteString(fmt.Sprintf("%v", _m.LearningStep))
	builder.WriteString(", ")
	builder.WriteString("review_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReviewCount))
	builder.WriteString(", ")
	builder.WriteString("lapse_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.LapseCount))
	builder.WriteString(", ")
	if v := _m.LastReviewedAt; v != nil {
		builder.WriteString("last_reviewed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// FlashcardReviews is a parsable slice of FlashcardReview.
type FlashcardReviews []*FlashcardReview
