// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/quanphung1120/advanced-quiz-be/ent/flashcardreview"
	"github.com/quanphung1120/advanced-quiz-be/ent/predicate"
)

// FlashcardReviewDelete is the builder for deleting a FlashcardReview entity.
type FlashcardReviewDelete struct {
	config
	hooks    []Hook
	mutation *FlashcardReviewMutation
}

// Where appends a list predicates to the FlashcardReviewDelete builder.
func (_d *FlashcardReviewDelete) Where(ps ...predicate.FlashcardReview) *FlashcardReviewDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *FlashcardReviewDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FlashcardReviewDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *FlashcardReviewDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(flashcardreview.Table, sqlgraph.NewFieldSpec(flashcardreview.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// FlashcardReviewDeleteOne is the builder for deleting a single FlashcardReview entity.
type FlashcardReviewDeleteOne struct {
	_d *FlashcardReviewDelete
}

// Where appends a list predicates to the FlashcardReviewDelete builder.
func (_d *FlashcardReviewDeleteOne) Where(ps ...predicate.FlashcardReview) *FlashcardReviewDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *FlashcardReviewDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{flashcardreview.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FlashcardReviewDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
