// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/quanphung1120/advanced-quiz-be/ent/collection"
	"github.com/quanphung1120/advanced-quiz-be/ent/collectioncollaborator"
	"github.com/quanphung1120/advanced-quiz-be/ent/flashcard"
	"github.com/quanphung1120/advanced-quiz-be/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeCollection             = "Collection"
	TypeCollectionCollaborator = "CollectionCollaborator"
	TypeFlashcard              = "Flashcard"
)

// CollectionMutation represents an operation that mutates the Collection nodes in the graph.
type CollectionMutation struct {
	config
	op                   Op
	typ                  string
	id                   *uuid.UUID
	name                 *string
	description          *string
	owner_id             *string
	is_public            *bool
	created_at           *time.Time
	updated_at           *time.Time
	clearedFields        map[string]struct{}
	collaborators        map[uuid.UUID]struct{}
	removedcollaborators map[uuid.UUID]struct{}
	clearedcollaborators bool
	flashcards           map[uuid.UUID]struct{}
	removedflashcards    map[uuid.UUID]struct{}
	clearedflashcards    bool
	done                 bool
	oldValue             func(context.Context) (*Collection, error)
	predicates           []predicate.Collection
}

var _ ent.Mutation = (*CollectionMutation)(nil)

// collectionOption allows management of the mutation configuration using functional options.
type collectionOption func(*CollectionMutation)

// newCollectionMutation creates new mutation for the Collection entity.
func newCollectionMutation(c config, op Op, opts ...collectionOption) *CollectionMutation {
	m := &CollectionMutation{
		config:        c,
		op:            op,
		typ:           TypeCollection,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withCollectionID sets the ID field of the mutation.
func withCollectionID(id uuid.UUID) collectionOption {
	return func(m *CollectionMutation) {
		var (
			err   error
			once  sync.Once
			value *Collection
		)
		m.oldValue = func(ctx context.Context) (*Collection, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Collection.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withCollection sets the old Collection of the mutation.
func withCollection(node *Collection) collectionOption {
	return func(m *CollectionMutation) {
		m.oldValue = func(context.Context) (*Collection, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m CollectionMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m CollectionMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Collection entities.
func (m *CollectionMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *CollectionMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *CollectionMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Collection.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *CollectionMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *CollectionMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Collection entity.
// If the Collection object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CollectionMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *CollectionMutation) ResetName() {
	m.name = nil
}

// SetDescription sets the "description" field.
func (m *CollectionMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *CollectionMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the Collection entity.
// If the Collection object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CollectionMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ClearDescription clears the value of the "description" field.
func (m *CollectionMutation) ClearDescription() {
	m.description = nil
	m.clearedFields[collection.FieldDescription] = struct{}{}
}

// DescriptionCleared returns if the "description" field was cleared in this mutation.
func (m *CollectionMutation) DescriptionCleared() bool {
	_, ok := m.clearedFields[collection.FieldDescription]
	return ok
}

// ResetDescription resets all changes to the "description" field.
func (m *CollectionMutation) ResetDescription() {
	m.description = nil
	delete(m.clearedFields, collection.FieldDescription)
}

// SetOwnerID sets the "owner_id" field.
func (m *CollectionMutation) SetOwnerID(s string) {
	m.owner_id = &s
}

// OwnerID returns the value of the "owner_id" field in the mutation.
func (m *CollectionMutation) OwnerID() (r string, exists bool) {
	v := m.owner_id
	if v == nil {
		return
	}
	return *v, true
}

// OldOwnerID returns the old "owner_id" field's value of the Collection entity.
// If the Collection object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CollectionMutation) OldOwnerID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOwnerID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOwnerID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOwnerID: %w", err)
	}
	return oldValue.OwnerID, nil
}

// ResetOwnerID resets all changes to the "owner_id" field.
func (m *CollectionMutation) ResetOwnerID() {
	m.owner_id = nil
}

// SetIsPublic sets the "is_public" field.
func (m *CollectionMutation) SetIsPublic(b bool) {
	m.is_public = &b
}

// IsPublic returns the value of the "is_public" field in the mutation.
func (m *CollectionMutation) IsPublic() (r bool, exists bool) {
	v := m.is_public
	if v == nil {
		return
	}
	return *v, true
}

// OldIsPublic returns the old "is_public" field's value of the Collection entity.
// If the Collection object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CollectionMutation) OldIsPublic(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsPublic is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsPublic requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsPublic: %w", err)
	}
	return oldValue.IsPublic, nil
}

// ResetIsPublic resets all changes to the "is_public" field.
func (m *CollectionMutation) ResetIsPublic() {
	m.is_public = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *CollectionMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *CollectionMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Collection entity.
// If the Collection object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CollectionMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *CollectionMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *CollectionMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *CollectionMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Collection entity.
// If the Collection object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CollectionMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *CollectionMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// AddCollaboratorIDs adds the "collaborators" edge to the CollectionCollaborator entity by ids.
func (m *CollectionMutation) AddCollaboratorIDs(ids ...uuid.UUID) {
	if m.collaborators == nil {
		m.collaborators = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.collaborators[ids[i]] = struct{}{}
	}
}

// ClearCollaborators clears the "collaborators" edge to the CollectionCollaborator entity.
func (m *CollectionMutation) ClearCollaborators() {
	m.clearedcollaborators = true
}

// CollaboratorsCleared reports if the "collaborators" edge to the CollectionCollaborator entity was cleared.
func (m *CollectionMutation) CollaboratorsCleared() bool {
	return m.clearedcollaborators
}

// RemoveCollaboratorIDs removes the "collaborators" edge to the CollectionCollaborator entity by IDs.
func (m *CollectionMutation) RemoveCollaboratorIDs(ids ...uuid.UUID) {
	if m.removedcollaborators == nil {
		m.removedcollaborators = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.collaborators, ids[i])
		m.removedcollaborators[ids[i]] = struct{}{}
	}
}

// RemovedCollaborators returns the removed IDs of the "collaborators" edge to the CollectionCollaborator entity.
func (m *CollectionMutation) RemovedCollaboratorsIDs() (ids []uuid.UUID) {
	for id := range m.removedcollaborators {
		ids = append(ids, id)
	}
	return
}

// CollaboratorsIDs returns the "collaborators" edge IDs in the mutation.
func (m *CollectionMutation) CollaboratorsIDs() (ids []uuid.UUID) {
	for id := range m.collaborators {
		ids = append(ids, id)
	}
	return
}

// ResetCollaborators resets all changes to the "collaborators" edge.
func (m *CollectionMutation) ResetCollaborators() {
	m.collaborators = nil
	m.clearedcollaborators = false
	m.removedcollaborators = nil
}

// AddFlashcardIDs adds the "flashcards" edge to the Flashcard entity by ids.
func (m *CollectionMutation) AddFlashcardIDs(ids ...uuid.UUID) {
	if m.flashcards == nil {
		m.flashcards = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.flashcards[ids[i]] = struct{}{}
	}
}

// ClearFlashcards clears the "flashcards" edge to the Flashcard entity.
func (m *CollectionMutation) ClearFlashcards() {
	m.clearedflashcards = true
}

// FlashcardsCleared reports if the "flashcards" edge to the Flashcard entity was cleared.
func (m *CollectionMutation) FlashcardsCleared() bool {
	return m.clearedflashcards
}

// RemoveFlashcardIDs removes the "flashcards" edge to the Flashcard entity by IDs.
func (m *CollectionMutation) RemoveFlashcardIDs(ids ...uuid.UUID) {
	if m.removedflashcards == nil {
		m.removedflashcards = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.flashcards, ids[i])
		m.removedflashcards[ids[i]] = struct{}{}
	}
}

// RemovedFlashcards returns the removed IDs of the "flashcards" edge to the Flashcard entity.
func (m *CollectionMutation) RemovedFlashcardsIDs() (ids []uuid.UUID) {
	for id := range m.removedflashcards {
		ids = append(ids, id)
	}
	return
}

// FlashcardsIDs returns the "flashcards" edge IDs in the mutation.
func (m *CollectionMutation) FlashcardsIDs() (ids []uuid.UUID) {
	for id := range m.flashcards {
		ids = append(ids, id)
	}
	return
}

// ResetFlashcards resets all changes to the "flashcards" edge.
func (m *CollectionMutation) ResetFlashcards() {
	m.flashcards = nil
	m.clearedflashcards = false
	m.removedflashcards = nil
}

// Where appends a list predicates to the CollectionMutation builder.
func (m *CollectionMutation) Where(ps ...predicate.Collection) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the CollectionMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *CollectionMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Collection, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *CollectionMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *CollectionMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Collection).
func (m *CollectionMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *CollectionMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.name != nil {
		fields = append(fields, collection.FieldName)
	}
	if m.description != nil {
		fields = append(fields, collection.FieldDescription)
	}
	if m.owner_id != nil {
		fields = append(fields, collection.FieldOwnerID)
	}
	if m.is_public != nil {
		fields = append(fields, collection.FieldIsPublic)
	}
	if m.created_at != nil {
		fields = append(fields, collection.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, collection.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *CollectionMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case collection.FieldName:
		return m.Name()
	case collection.FieldDescription:
		return m.Description()
	case collection.FieldOwnerID:
		return m.OwnerID()
	case collection.FieldIsPublic:
		return m.IsPublic()
	case collection.FieldCreatedAt:
		return m.CreatedAt()
	case collection.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *CollectionMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case collection.FieldName:
		return m.OldName(ctx)
	case collection.FieldDescription:
		return m.OldDescription(ctx)
	case collection.FieldOwnerID:
		return m.OldOwnerID(ctx)
	case collection.FieldIsPublic:
		return m.OldIsPublic(ctx)
	case collection.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case collection.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Collection field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CollectionMutation) SetField(name string, value ent.Value) error {
	switch name {
	case collection.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case collection.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case collection.FieldOwnerID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOwnerID(v)
		return nil
	case collection.FieldIsPublic:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsPublic(v)
		return nil
	case collection.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case collection.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Collection field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *CollectionMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *CollectionMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CollectionMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Collection numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *CollectionMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(collection.FieldDescription) {
		fields = append(fields, collection.FieldDescription)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *CollectionMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *CollectionMutation) ClearField(name string) error {
	switch name {
	case collection.FieldDescription:
		m.ClearDescription()
		return nil
	}
	return fmt.Errorf("unknown Collection nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *CollectionMutation) ResetField(name string) error {
	switch name {
	case collection.FieldName:
		m.ResetName()
		return nil
	case collection.FieldDescription:
		m.ResetDescription()
		return nil
	case collection.FieldOwnerID:
		m.ResetOwnerID()
		return nil
	case collection.FieldIsPublic:
		m.ResetIsPublic()
		return nil
	case collection.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case collection.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Collection field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *CollectionMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.collaborators != nil {
		edges = append(edges, collection.EdgeCollaborators)
	}
	if m.flashcards != nil {
		edges = append(edges, collection.EdgeFlashcards)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *CollectionMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case collection.EdgeCollaborators:
		ids := make([]ent.Value, 0, len(m.collaborators))
		for id := range m.collaborators {
			ids = append(ids, id)
		}
		return ids
	case collection.EdgeFlashcards:
		ids := make([]ent.Value, 0, len(m.flashcards))
		for id := range m.flashcards {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *CollectionMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedcollaborators != nil {
		edges = append(edges, collection.EdgeCollaborators)
	}
	if m.removedflashcards != nil {
		edges = append(edges, collection.EdgeFlashcards)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *CollectionMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case collection.EdgeCollaborators:
		ids := make([]ent.Value, 0, len(m.removedcollaborators))
		for id := range m.removedcollaborators {
			ids = append(ids, id)
		}
		return ids
	case collection.EdgeFlashcards:
		ids := make([]ent.Value, 0, len(m.removedflashcards))
		for id := range m.removedflashcards {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *CollectionMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedcollaborators {
		edges = append(edges, collection.EdgeCollaborators)
	}
	if m.clearedflashcards {
		edges = append(edges, collection.EdgeFlashcards)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *CollectionMutation) EdgeCleared(name string) bool {
	switch name {
	case collection.EdgeCollaborators:
		return m.clearedcollaborators
	case collection.EdgeFlashcards:
		return m.clearedflashcards
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *CollectionMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Collection unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *CollectionMutation) ResetEdge(name string) error {
	switch name {
	case collection.EdgeCollaborators:
		m.ResetCollaborators()
		return nil
	case collection.EdgeFlashcards:
		m.ResetFlashcards()
		return nil
	}
	return fmt.Errorf("unknown Collection edge %s", name)
}

// CollectionCollaboratorMutation represents an operation that mutates the CollectionCollaborator nodes in the graph.
type CollectionCollaboratorMutation struct {
	config
	op                Op
	typ               string
	id                *uuid.UUID
	user_id           *string
	role              *string
	created_at        *time.Time
	clearedFields     map[string]struct{}
	collection        *uuid.UUID
	clearedcollection bool
	done              bool
	oldValue          func(context.Context) (*CollectionCollaborator, error)
	predicates        []predicate.CollectionCollaborator
}

var _ ent.Mutation = (*CollectionCollaboratorMutation)(nil)

// collectioncollaboratorOption allows management of the mutation configuration using functional options.
type collectioncollaboratorOption func(*CollectionCollaboratorMutation)

// newCollectionCollaboratorMutation creates new mutation for the CollectionCollaborator entity.
func newCollectionCollaboratorMutation(c config, op Op, opts ...collectioncollaboratorOption) *CollectionCollaboratorMutation {
	m := &CollectionCollaboratorMutation{
		config:        c,
		op:            op,
		typ:           TypeCollectionCollaborator,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withCollectionCollaboratorID sets the ID field of the mutation.
func withCollectionCollaboratorID(id uuid.UUID) collectioncollaboratorOption {
	return func(m *CollectionCollaboratorMutation) {
		var (
			err   error
			once  sync.Once
			value *CollectionCollaborator
		)
		m.oldValue = func(ctx context.Context) (*CollectionCollaborator, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().CollectionCollaborator.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withCollectionCollaborator sets the old CollectionCollaborator of the mutation.
func withCollectionCollaborator(node *CollectionCollaborator) collectioncollaboratorOption {
	return func(m *CollectionCollaboratorMutation) {
		m.oldValue = func(context.Context) (*CollectionCollaborator, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m CollectionCollaboratorMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m CollectionCollaboratorMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of CollectionCollaborator entities.
func (m *CollectionCollaboratorMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *CollectionCollaboratorMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *CollectionCollaboratorMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().CollectionCollaborator.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCollectionID sets the "collection_id" field.
func (m *CollectionCollaboratorMutation) SetCollectionID(u uuid.UUID) {
	m.collection = &u
}

// CollectionID returns the value of the "collection_id" field in the mutation.
func (m *CollectionCollaboratorMutation) CollectionID() (r uuid.UUID, exists bool) {
	v := m.collection
	if v == nil {
		return
	}
	return *v, true
}

// OldCollectionID returns the old "collection_id" field's value of the CollectionCollaborator entity.
// If the CollectionCollaborator object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CollectionCollaboratorMutation) OldCollectionID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCollectionID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCollectionID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCollectionID: %w", err)
	}
	return oldValue.CollectionID, nil
}

// ResetCollectionID resets all changes to the "collection_id" field.
func (m *CollectionCollaboratorMutation) ResetCollectionID() {
	m.collection = nil
}

// SetUserID sets the "user_id" field.
func (m *CollectionCollaboratorMutation) SetUserID(s string) {
	m.user_id = &s
}

// UserID returns the value of the "user_id" field in the mutation.
func (m *CollectionCollaboratorMutation) UserID() (r string, exists bool) {
	v := m.user_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUserID returns the old "user_id" field's value of the CollectionCollaborator entity.
// If the CollectionCollaborator object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CollectionCollaboratorMutation) OldUserID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserID: %w", err)
	}
	return oldValue.UserID, nil
}

// ResetUserID resets all changes to the "user_id" field.
func (m *CollectionCollaboratorMutation) ResetUserID() {
	m.user_id = nil
}

// SetRole sets the "role" field.
func (m *CollectionCollaboratorMutation) SetRole(s string) {
	m.role = &s
}

// Role returns the value of the "role" field in the mutation.
func (m *CollectionCollaboratorMutation) Role() (r string, exists bool) {
	v := m.role
	if v == nil {
		return
	}
	return *v, true
}

// OldRole returns the old "role" field's value of the CollectionCollaborator entity.
// If the CollectionCollaborator object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CollectionCollaboratorMutation) OldRole(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRole is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRole requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRole: %w", err)
	}
	return oldValue.Role, nil
}

// ResetRole resets all changes to the "role" field.
func (m *CollectionCollaboratorMutation) ResetRole() {
	m.role = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *CollectionCollaboratorMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *CollectionCollaboratorMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the CollectionCollaborator entity.
// If the CollectionCollaborator object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CollectionCollaboratorMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *CollectionCollaboratorMutation) ResetCreatedAt() {
	m.created_at = nil
}

// ClearCollection clears the "collection" edge to the Collection entity.
func (m *CollectionCollaboratorMutation) ClearCollection() {
	m.clearedcollection = true
	m.clearedFields[collectioncollaborator.FieldCollectionID] = struct{}{}
}

// CollectionCleared reports if the "collection" edge to the Collection entity was cleared.
func (m *CollectionCollaboratorMutation) CollectionCleared() bool {
	return m.clearedcollection
}

// CollectionIDs returns the "collection" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// CollectionID instead. It exists only for internal usage by the builders.
func (m *CollectionCollaboratorMutation) CollectionIDs() (ids []uuid.UUID) {
	if id := m.collection; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetCollection resets all changes to the "collection" edge.
func (m *CollectionCollaboratorMutation) ResetCollection() {
	m.collection = nil
	m.clearedcollection = false
}

// Where appends a list predicates to the CollectionCollaboratorMutation builder.
func (m *CollectionCollaboratorMutation) Where(ps ...predicate.CollectionCollaborator) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the CollectionCollaboratorMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *CollectionCollaboratorMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.CollectionCollaborator, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *CollectionCollaboratorMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *CollectionCollaboratorMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (CollectionCollaborator).
func (m *CollectionCollaboratorMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *CollectionCollaboratorMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.collection != nil {
		fields = append(fields, collectioncollaborator.FieldCollectionID)
	}
	if m.user_id != nil {
		fields = append(fields, collectioncollaborator.FieldUserID)
	}
	if m.role != nil {
		fields = append(fields, collectioncollaborator.FieldRole)
	}
	if m.created_at != nil {
		fields = append(fields, collectioncollaborator.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *CollectionCollaboratorMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case collectioncollaborator.FieldCollectionID:
		return m.CollectionID()
	case collectioncollaborator.FieldUserID:
		return m.UserID()
	case collectioncollaborator.FieldRole:
		return m.Role()
	case collectioncollaborator.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *CollectionCollaboratorMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case collectioncollaborator.FieldCollectionID:
		return m.OldCollectionID(ctx)
	case collectioncollaborator.FieldUserID:
		return m.OldUserID(ctx)
	case collectioncollaborator.FieldRole:
		return m.OldRole(ctx)
	case collectioncollaborator.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown CollectionCollaborator field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CollectionCollaboratorMutation) SetField(name string, value ent.Value) error {
	switch name {
	case collectioncollaborator.FieldCollectionID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCollectionID(v)
		return nil
	case collectioncollaborator.FieldUserID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserID(v)
		return nil
	case collectioncollaborator.FieldRole:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRole(v)
		return nil
	case collectioncollaborator.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown CollectionCollaborator field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *CollectionCollaboratorMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *CollectionCollaboratorMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CollectionCollaboratorMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown CollectionCollaborator numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *CollectionCollaboratorMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *CollectionCollaboratorMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *CollectionCollaboratorMutation) ClearField(name string) error {
	return fmt.Errorf("unknown CollectionCollaborator nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *CollectionCollaboratorMutation) ResetField(name string) error {
	switch name {
	case collectioncollaborator.FieldCollectionID:
		m.ResetCollectionID()
		return nil
	case collectioncollaborator.FieldUserID:
		m.ResetUserID()
		return nil
	case collectioncollaborator.FieldRole:
		m.ResetRole()
		return nil
	case collectioncollaborator.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown CollectionCollaborator field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *CollectionCollaboratorMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.collection != nil {
		edges = append(edges, collectioncollaborator.EdgeCollection)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *CollectionCollaboratorMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case collectioncollaborator.EdgeCollection:
		if id := m.collection; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *CollectionCollaboratorMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *CollectionCollaboratorMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *CollectionCollaboratorMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedcollection {
		edges = append(edges, collectioncollaborator.EdgeCollection)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *CollectionCollaboratorMutation) EdgeCleared(name string) bool {
	switch name {
	case collectioncollaborator.EdgeCollection:
		return m.clearedcollection
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *CollectionCollaboratorMutation) ClearEdge(name string) error {
	switch name {
	case collectioncollaborator.EdgeCollection:
		m.ClearCollection()
		return nil
	}
	return fmt.Errorf("unknown CollectionCollaborator unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *CollectionCollaboratorMutation) ResetEdge(name string) error {
	switch name {
	case collectioncollaborator.EdgeCollection:
		m.ResetCollection()
		return nil
	}
	return fmt.Errorf("unknown CollectionCollaborator edge %s", name)
}

// FlashcardMutation represents an operation that mutates the Flashcard nodes in the graph.
type FlashcardMutation struct {
	config
	op                Op
	typ               string
	id                *uuid.UUID
	question          *string
	answer            *string
	_type             *string
	created_by        *string
	created_at        *time.Time
	updated_at        *time.Time
	clearedFields     map[string]struct{}
	collection        *uuid.UUID
	clearedcollection bool
	done              bool
	oldValue          func(context.Context) (*Flashcard, error)
	predicates        []predicate.Flashcard
}

var _ ent.Mutation = (*FlashcardMutation)(nil)

// flashcardOption allows management of the mutation configuration using functional options.
type flashcardOption func(*FlashcardMutation)

// newFlashcardMutation creates new mutation for the Flashcard entity.
func newFlashcardMutation(c config, op Op, opts ...flashcardOption) *FlashcardMutation {
	m := &FlashcardMutation{
		config:        c,
		op:            op,
		typ:           TypeFlashcard,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withFlashcardID sets the ID field of the mutation.
func withFlashcardID(id uuid.UUID) flashcardOption {
	return func(m *FlashcardMutation) {
		var (
			err   error
			once  sync.Once
			value *Flashcard
		)
		m.oldValue = func(ctx context.Context) (*Flashcard, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Flashcard.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withFlashcard sets the old Flashcard of the mutation.
func withFlashcard(node *Flashcard) flashcardOption {
	return func(m *FlashcardMutation) {
		m.oldValue = func(context.Context) (*Flashcard, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m FlashcardMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m FlashcardMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Flashcard entities.
func (m *FlashcardMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *FlashcardMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *FlashcardMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Flashcard.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetQuestion sets the "question" field.
func (m *FlashcardMutation) SetQuestion(s string) {
	m.question = &s
}

// Question returns the value of the "question" field in the mutation.
func (m *FlashcardMutation) Question() (r string, exists bool) {
	v := m.question
	if v == nil {
		return
	}
	return *v, true
}

// OldQuestion returns the old "question" field's value of the Flashcard entity.
// If the Flashcard object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlashcardMutation) OldQuestion(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldQuestion is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldQuestion requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldQuestion: %w", err)
	}
	return oldValue.Question, nil
}

// ResetQuestion resets all changes to the "question" field.
func (m *FlashcardMutation) ResetQuestion() {
	m.question = nil
}

// SetAnswer sets the "answer" field.
func (m *FlashcardMutation) SetAnswer(s string) {
	m.answer = &s
}

// Answer returns the value of the "answer" field in the mutation.
func (m *FlashcardMutation) Answer() (r string, exists bool) {
	v := m.answer
	if v == nil {
		return
	}
	return *v, true
}

// OldAnswer returns the old "answer" field's value of the Flashcard entity.
// If the Flashcard object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlashcardMutation) OldAnswer(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAnswer is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAnswer requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAnswer: %w", err)
	}
	return oldValue.Answer, nil
}

// ResetAnswer resets all changes to the "answer" field.
func (m *FlashcardMutation) ResetAnswer() {
	m.answer = nil
}

// SetType sets the "type" field.
func (m *FlashcardMutation) SetType(s string) {
	m._type = &s
}

// GetType returns the value of the "type" field in the mutation.
func (m *FlashcardMutation) GetType() (r string, exists bool) {
	v := m._type
	if v == nil {
		return
	}
	return *v, true
}

// OldType returns the old "type" field's value of the Flashcard entity.
// If the Flashcard object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlashcardMutation) OldType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldType: %w", err)
	}
	return oldValue.Type, nil
}

// ResetType resets all changes to the "type" field.
func (m *FlashcardMutation) ResetType() {
	m._type = nil
}

// SetCollectionID sets the "collection_id" field.
func (m *FlashcardMutation) SetCollectionID(u uuid.UUID) {
	m.collection = &u
}

// CollectionID returns the value of the "collection_id" field in the mutation.
func (m *FlashcardMutation) CollectionID() (r uuid.UUID, exists bool) {
	v := m.collection
	if v == nil {
		return
	}
	return *v, true
}

// OldCollectionID returns the old "collection_id" field's value of the Flashcard entity.
// If the Flashcard object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlashcardMutation) OldCollectionID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCollectionID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCollectionID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCollectionID: %w", err)
	}
	return oldValue.CollectionID, nil
}

// ResetCollectionID resets all changes to the "collection_id" field.
func (m *FlashcardMutation) ResetCollectionID() {
	m.collection = nil
}

// SetCreatedBy sets the "created_by" field.
func (m *FlashcardMutation) SetCreatedBy(s string) {
	m.created_by = &s
}

// CreatedBy returns the value of the "created_by" field in the mutation.
func (m *FlashcardMutation) CreatedBy() (r string, exists bool) {
	v := m.created_by
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedBy returns the old "created_by" field's value of the Flashcard entity.
// If the Flashcard object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlashcardMutation) OldCreatedBy(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedBy: %w", err)
	}
	return oldValue.CreatedBy, nil
}

// ResetCreatedBy resets all changes to the "created_by" field.
func (m *FlashcardMutation) ResetCreatedBy() {
	m.created_by = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *FlashcardMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *FlashcardMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Flashcard entity.
// If the Flashcard object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlashcardMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *FlashcardMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *FlashcardMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *FlashcardMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Flashcard entity.
// If the Flashcard object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FlashcardMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *FlashcardMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// ClearCollection clears the "collection" edge to the Collection entity.
func (m *FlashcardMutation) ClearCollection() {
	m.clearedcollection = true
	m.clearedFields[flashcard.FieldCollectionID] = struct{}{}
}

// CollectionCleared reports if the "collection" edge to the Collection entity was cleared.
func (m *FlashcardMutation) CollectionCleared() bool {
	return m.clearedcollection
}

// CollectionIDs returns the "collection" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// CollectionID instead. It exists only for internal usage by the builders.
func (m *FlashcardMutation) CollectionIDs() (ids []uuid.UUID) {
	if id := m.collection; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetCollection resets all changes to the "collection" edge.
func (m *FlashcardMutation) ResetCollection() {
	m.collection = nil
	m.clearedcollection = false
}

// Where appends a list predicates to the FlashcardMutation builder.
func (m *FlashcardMutation) Where(ps ...predicate.Flashcard) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the FlashcardMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *FlashcardMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Flashcard, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *FlashcardMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *FlashcardMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Flashcard).
func (m *FlashcardMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *FlashcardMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.question != nil {
		fields = append(fields, flashcard.FieldQuestion)
	}
	if m.answer != nil {
		fields = append(fields, flashcard.FieldAnswer)
	}
	if m._type != nil {
		fields = append(fields, flashcard.FieldType)
	}
	if m.collection != nil {
		fields = append(fields, flashcard.FieldCollectionID)
	}
	if m.created_by != nil {
		fields = append(fields, flashcard.FieldCreatedBy)
	}
	if m.created_at != nil {
		fields = append(fields, flashcard.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, flashcard.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *FlashcardMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case flashcard.FieldQuestion:
		return m.Question()
	case flashcard.FieldAnswer:
		return m.Answer()
	case flashcard.FieldType:
		return m.GetType()
	case flashcard.FieldCollectionID:
		return m.CollectionID()
	case flashcard.FieldCreatedBy:
		return m.CreatedBy()
	case flashcard.FieldCreatedAt:
		return m.CreatedAt()
	case flashcard.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *FlashcardMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case flashcard.FieldQuestion:
		return m.OldQuestion(ctx)
	case flashcard.FieldAnswer:
		return m.OldAnswer(ctx)
	case flashcard.FieldType:
		return m.OldType(ctx)
	case flashcard.FieldCollectionID:
		return m.OldCollectionID(ctx)
	case flashcard.FieldCreatedBy:
		return m.OldCreatedBy(ctx)
	case flashcard.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case flashcard.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Flashcard field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FlashcardMutation) SetField(name string, value ent.Value) error {
	switch name {
	case flashcard.FieldQuestion:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetQuestion(v)
		return nil
	case flashcard.FieldAnswer:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAnswer(v)
		return nil
	case flashcard.FieldType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetType(v)
		return nil
	case flashcard.FieldCollectionID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCollectionID(v)
		return nil
	case flashcard.FieldCreatedBy:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedBy(v)
		return nil
	case flashcard.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case flashcard.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Flashcard field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *FlashcardMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *FlashcardMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FlashcardMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Flashcard numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *FlashcardMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *FlashcardMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *FlashcardMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Flashcard nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *FlashcardMutation) ResetField(name string) error {
	switch name {
	case flashcard.FieldQuestion:
		m.ResetQuestion()
		return nil
	case flashcard.FieldAnswer:
		m.ResetAnswer()
		return nil
	case flashcard.FieldType:
		m.ResetType()
		return nil
	case flashcard.FieldCollectionID:
		m.ResetCollectionID()
		return nil
	case flashcard.FieldCreatedBy:
		m.ResetCreatedBy()
		return nil
	case flashcard.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case flashcard.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Flashcard field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *FlashcardMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.collection != nil {
		edges = append(edges, flashcard.EdgeCollection)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *FlashcardMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case flashcard.EdgeCollection:
		if id := m.collection; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *FlashcardMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *FlashcardMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *FlashcardMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedcollection {
		edges = append(edges, flashcard.EdgeCollection)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *FlashcardMutation) EdgeCleared(name string) bool {
	switch name {
	case flashcard.EdgeCollection:
		return m.clearedcollection
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *FlashcardMutation) ClearEdge(name string) error {
	switch name {
	case flashcard.EdgeCollection:
		m.ClearCollection()
		return nil
	}
	return fmt.Errorf("unknown Flashcard unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *FlashcardMutation) ResetEdge(name string) error {
	switch name {
	case flashcard.EdgeCollection:
		m.ResetCollection()
		return nil
	}
	return fmt.Errorf("unknown Flashcard edge %s", name)
}
