// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/quanphung1120/advanced-quiz-be/ent/collection"
	"github.com/quanphung1120/advanced-quiz-be/ent/collectioncollaborator"
	"github.com/quanphung1120/advanced-quiz-be/ent/flashcard"
	"github.com/quanphung1120/advanced-quiz-be/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	collectionFields := schema.Collection{}.Fields()
	_ = collectionFields
	// collectionDescName is the schema descriptor for name field.
	collectionDescName := collectionFields[1].Descriptor()
	// collection.NameValidator is a validator for the "name" field. It is called by the builders before save.
	collection.NameValidator = func() func(string) error {
		validators := collectionDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// collectionDescDescription is the schema descriptor for description field.
	collectionDescDescription := collectionFields[2].Descriptor()
	// collection.DefaultDescription holds the default value on creation for the description field.
	collection.DefaultDescription = collectionDescDescription.Default.(string)
	// collectionDescOwnerID is the schema descriptor for owner_id field.
	collectionDescOwnerID := collectionFields[3].Descriptor()
	// collection.OwnerIDValidator is a validator for the "owner_id" field. It is called by the builders before save.
	collection.OwnerIDValidator = func() func(string) error {
		validators := collectionDescOwnerID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(owner_id string) error {
			for _, fn := range fns {
				if err := fn(owner_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// collectionDescIsPublic is the schema descriptor for is_public field.
	collectionDescIsPublic := collectionFields[4].Descriptor()
	// collection.DefaultIsPublic holds the default value on creation for the is_public field.
	collection.DefaultIsPublic = collectionDescIsPublic.Default.(bool)
	// collectionDescCreatedAt is the schema descriptor for created_at field.
	collectionDescCreatedAt := collectionFields[5].Descriptor()
	// collection.DefaultCreatedAt holds the default value on creation for the created_at field.
	collection.DefaultCreatedAt = collectionDescCreatedAt.Default.(func() time.Time)
	// collectionDescUpdatedAt is the schema descriptor for updated_at field.
	collectionDescUpdatedAt := collectionFields[6].Descriptor()
	// collection.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	collection.DefaultUpdatedAt = collectionDescUpdatedAt.Default.(func() time.Time)
	// collection.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	collection.UpdateDefaultUpdatedAt = collectionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// collectionDescID is the schema descriptor for id field.
	collectionDescID := collectionFields[0].Descriptor()
	// collection.DefaultID holds the default value on creation for the id field.
	collection.DefaultID = collectionDescID.Default.(func() uuid.UUID)
	collectioncollaboratorFields := schema.CollectionCollaborator{}.Fields()
	_ = collectioncollaboratorFields
	// collectioncollaboratorDescUserID is the schema descriptor for user_id field.
	collectioncollaboratorDescUserID := collectioncollaboratorFields[2].Descriptor()
	// collectioncollaborator.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	collectioncollaborator.UserIDValidator = func() func(string) error {
		validators := collectioncollaboratorDescUserID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(user_id string) error {
			for _, fn := range fns {
				if err := fn(user_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// collectioncollaboratorDescRole is the schema descriptor for role field.
	collectioncollaboratorDescRole := collectioncollaboratorFields[3].Descriptor()
	// collectioncollaborator.DefaultRole holds the default value on creation for the role field.
	collectioncollaborator.DefaultRole = collectioncollaboratorDescRole.Default.(string)
	// collectioncollaborator.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	collectioncollaborator.RoleValidator = collectioncollaboratorDescRole.Validators[0].(func(string) error)
	// collectioncollaboratorDescCreatedAt is the schema descriptor for created_at field.
	collectioncollaboratorDescCreatedAt := collectioncollaboratorFields[4].Descriptor()
	// collectioncollaborator.DefaultCreatedAt holds the default value on creation for the created_at field.
	collectioncollaborator.DefaultCreatedAt = collectioncollaboratorDescCreatedAt.Default.(func() time.Time)
	// collectioncollaboratorDescID is the schema descriptor for id field.
	collectioncollaboratorDescID := collectioncollaboratorFields[0].Descriptor()
	// collectioncollaborator.DefaultID holds the default value on creation for the id field.
	collectioncollaborator.DefaultID = collectioncollaboratorDescID.Default.(func() uuid.UUID)
	flashcardFields := schema.Flashcard{}.Fields()
	_ = flashcardFields
	// flashcardDescQuestion is the schema descriptor for question field.
	flashcardDescQuestion := flashcardFields[1].Descriptor()
	// flashcard.QuestionValidator is a validator for the "question" field. It is called by the builders before save.
	flashcard.QuestionValidator = flashcardDescQuestion.Validators[0].(func(string) error)
	// flashcardDescAnswer is the schema descriptor for answer field.
	flashcardDescAnswer := flashcardFields[2].Descriptor()
	// flashcard.AnswerValidator is a validator for the "answer" field. It is called by the builders before save.
	flashcard.AnswerValidator = flashcardDescAnswer.Validators[0].(func(string) error)
	// flashcardDescType is the schema descriptor for type field.
	flashcardDescType := flashcardFields[3].Descriptor()
	// flashcard.DefaultType holds the default value on creation for the type field.
	flashcard.DefaultType = flashcardDescType.Default.(string)
	// flashcard.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	flashcard.TypeValidator = flashcardDescType.Validators[0].(func(string) error)
	// flashcardDescCreatedBy is the schema descriptor for created_by field.
	flashcardDescCreatedBy := flashcardFields[5].Descriptor()
	// flashcard.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	flashcard.CreatedByValidator = func() func(string) error {
		validators := flashcardDescCreatedBy.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(created_by string) error {
			for _, fn := range fns {
				if err := fn(created_by); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// flashcardDescCreatedAt is the schema descriptor for created_at field.
	flashcardDescCreatedAt := flashcardFields[6].Descriptor()
	// flashcard.DefaultCreatedAt holds the default value on creation for the created_at field.
	flashcard.DefaultCreatedAt = flashcardDescCreatedAt.Default.(func() time.Time)
	// flashcardDescUpdatedAt is the schema descriptor for updated_at field.
	flashcardDescUpdatedAt := flashcardFields[7].Descriptor()
	// flashcard.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	flashcard.DefaultUpdatedAt = flashcardDescUpdatedAt.Default.(func() time.Time)
	// flashcard.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	flashcard.UpdateDefaultUpdatedAt = flashcardDescUpdatedAt.UpdateDefault.(func() time.Time)
	// flashcardDescID is the schema descriptor for id field.
	flashcardDescID := flashcardFields[0].Descriptor()
	// flashcard.DefaultID holds the default value on creation for the id field.
	flashcard.DefaultID = flashcardDescID.Default.(func() uuid.UUID)
}
