export const ACCESS_TOKEN_TTL_SECONDS = 15 * 60;
export const REFRESH_TOKEN_TTL = "7d";
export const EMAIL_OTP_EXPIRY_MINUTES = 10;
export const PASSWORD_RESET_EXPIRY_MINUTES = 30;
export const EMAIL_OTP_RESEND_COOLDOWN_SECONDS = 60;
export const PASSWORD_RESET_RESEND_COOLDOWN_SECONDS = 60;
export const MAX_OTP_ATTEMPTS = 5;
