// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Collection is the predicate function for collection builders.
type Collection func(*sql.Selector)

// CollectionCollaborator is the predicate function for collectioncollaborator builders.
type CollectionCollaborator func(*sql.Selector)

// Flashcard is the predicate function for flashcard builders.
type Flashcard func(*sql.Selector)

// FlashcardReview is the predicate function for flashcardreview builders.
type FlashcardReview func(*sql.Selector)
